export const perPro = {"[Abl_Mod][1Du]":["wangkugnek"],"[Abl_Mod][1Pl]":["wangkutnek"],"[Abl_Mod][1Sg]":["wangnek"],"[Abl_Mod][2Du]":["elpetegnek"],"[Abl_Mod][2Pl]":["elpecnek"],"[Abl_Mod][2Sg]":["elpenek"],"[Abl_Mod][3Du]":["elkegnek"],"[Abl_Mod][3Pl]":["ellaitnek"],"[Abl_Mod][3Sg]":["elliinek"],"[Abl_Mod][4Du]":["ellmegnek"],"[Abl_Mod][4Pl]":["ellmeggnek"],"[Abl_Mod][4Sg]":["ellminek"],"[Abs][1Du]":["wangkuk"],"[Abs][1Pl]":["wangkuta"],"[Abs][1Sg]":["wii","wiinga"],"[Abs][2Du]":["elpetek"],"[Abs][2Pl]":["elpeci"],"[Abs][2Sg]":["elpet"],"[Abs][3Du]":["elkek"],"[Abs][3Pl]":["ellait"],"[Abs][3Sg]":["ellii"],"[Abs][4Du]":["ellmek"],"[Abs][4Pl]":["ellmeng"],"[Abs][4Sg]":["ellmi"],"[Equ][1Du]":["wangkugcetun","wangkugtun"],"[Equ][1Pl]":["wangkucetun","wangkutun"],"[Equ][1Sg]":["wangcetun","wangtun"],"[Equ][2Du]":["elpetegcetun","elpetegtun"],"[Equ][2Pl]":["elpecicetun","elpecitun"],"[Equ][2Sg]":["elpecetun","elpetun"],"[Equ][3Du]":["elkegcetun","elkegtun"],"[Equ][3Pl]":["ellaicetun","ellaitun"],"[Equ][3Sg]":["elliicetun","elliitun"],"[Equ][4Du]":["ellmegnegun"],"[Equ][4Pl]":["ellmegcetun","ellmegtun"],"[Equ][4Sg]":["ellmicetun","ellmitun"],"[Loc][1Du]":["wangkugni"],"[Loc][1Pl]":["wangkutni"],"[Loc][1Sg]":["wangni"],"[Loc][2Du]":["elpetegni"],"[Loc][2Pl]":["elpecni"],"[Loc][2Sg]":["elpeni"],"[Loc][3Du]":["elkegni"],"[Loc][3Pl]":["ellaitni"],"[Loc][3Sg]":["elliini"],"[Loc][4Du]":["ellmegni"],"[Loc][4Pl]":["ellmeggni"],"[Loc][4Sg]":["ellmini"],"[Rel][1Du]":["wangkuk"],"[Rel][1Pl]":["wangkuta"],"[Rel][1Sg]":["wii","wiinga"],"[Rel][2Du]":["elpetek"],"[Rel][2Pl]":["elpeci"],"[Rel][2Sg]":["elpet"],"[Rel][3Du]":["elkenka"],"[Rel][3Pl]":["ellaita"],"[Rel][3Sg]":["elliin"],"[Rel][4Du]":["ellmek"],"[Rel][4Pl]":["ellmeng"],"[Rel][4Sg]":["ellmi"],"[Ter][1Du]":["wangkugnun"],"[Ter][1Pl]":["wangkutnun"],"[Ter][1Sg]":["wangnun"],"[Ter][2Du]":["elpetegnun"],"[Ter][2Pl]":["elpecnun"],"[Ter][2Sg]":["elpenun"],"[Ter][3Du]":["elkegnun"],"[Ter][3Pl]":["ellaitnun"],"[Ter][3Sg]":["elliinun"],"[Ter][4Du]":["ellmegnun"],"[Ter][4Pl]":["ellmeggnun"],"[Ter][4Sg]":["ellminun"],"[Via][1Du]":["wangkugnegun"],"[Via][1Pl]":["wangkutgun"],"[Via][1Sg]":["wangkun"],"[Via][2Du]":["elpetegnegun"],"[Via][2Pl]":["elpecetgun"],"[Via][2Sg]":["elpetgun"],"[Via][3Du]":["elkegnegun"],"[Via][3Pl]":["ellaitgun"],"[Via][3Sg]":["elliikun"],"[Via][4Du]":["ellmegnegun"],"[Via][4Pl]":["ellmegteggun"],"[Via][4Sg]":["ellmikun"]}

export const demPro = {"across there":{"extended":{"=i[Encl]":["agaa-i","ii-i"],"[Abl]":["iiken","agaaken"],"[Abl_Mod][DuUnpd]":["agkugnek"],"[Abl_Mod][PlUnpd]":["agkunek"],"[Abl_Mod][SgUnpd]":["ag'umek"],"[Abs][DuUnpd]":["agkuk"],"[Abs][PlUnpd]":["agkut"],"[Abs][SgUnpd]":["agna"],"[Equ][DuUnpd]":["agkugcetun"],"[Equ][PlUnpd]":["agkucetun"],"[Equ][SgUnpd]":["ag'utun"],"[Loc]":["agaani","iini"],"[Loc][DuUnpd]":["agkugni"],"[Loc][PlUnpd]":["agkuni"],"[Loc][SgUnpd]":["ag'umi"],"[Rel][DuUnpd]":["agkuk"],"[Rel][PlUnpd]":["agkut"],"[Rel][SgUnpd]":["ag'um"],"[Sec_Ter]":["agaatmun","iitmun"],"[Ter]":["agaavet","iivet"],"[Ter][DuUnpd]":["agkugnun"],"[Ter][PlUnpd]":["agkunun"],"[Ter][SgUnpd]":["ag'umun"],"[Via]":["iiggun","agaaggun"],"[Via][DuUnpd]":["agkunegnun"],"[Via][PlUnpd]":["agkutgun"],"[Via][SgUnpd]":["ag'ukun"],"[Voc][DuUnpd]":["agkuuk"],"[Voc][PlUnpd]":["agkuut"],"[Voc][SgUnpd]":["agyuuq","agsuuq"]},"obscured":{"=i[Encl]":["akma-i"],"[Abl]":["akmaken"],"[Abl_Mod][DuUnpd]":["akemkugnek"],"[Abl_Mod][PlUnpd]":["akemkunek"],"[Abl_Mod][SgUnpd]":["ak'mumek"],"[Abs][DuUnpd]":["akemkuk"],"[Abs][PlUnpd]":["akemkut"],"[Abs][SgUnpd]":["akemna"],"[Equ][DuUnpd]":["akemkugcetun"],"[Equ][PlUnpd]":["akemkucetun"],"[Equ][SgUnpd]":["ak'mutun"],"[Loc]":["akmani"],"[Loc][DuUnpd]":["akemkugni"],"[Loc][PlUnpd]":["akemkuni"],"[Loc][SgUnpd]":["ak'mumi"],"[Rel][DuUnpd]":["akemkuk"],"[Rel][PlUnpd]":["akemkut"],"[Rel][SgUnpd]":["ak'mum"],"[Sec_Ter]":["-"],"[Ter]":["akmavet"],"[Ter][DuUnpd]":["akemkugnun"],"[Ter][PlUnpd]":["akemkunun"],"[Ter][SgUnpd]":["ak'mumun"],"[Via]":["akmaggun"],"[Via][DuUnpd]":["akemkunegnun"],"[Via][PlUnpd]":["akemkutgun"],"[Via][SgUnpd]":["ak'mukun"],"[Voc][DuUnpd]":["akemkuuk"],"[Voc][PlUnpd]":["akemkuut"],"[Voc][SgUnpd]":["akemsuuq","akemyuuq"]},"restricted":{"=i[Encl]":["ika-i"],"[Abl]":["ikaken"],"[Abl_Mod][DuUnpd]":["ikegkugnek"],"[Abl_Mod][PlUnpd]":["ikegkunek"],"[Abl_Mod][SgUnpd]":["ik'umek","ikgumek"],"[Abs][DuUnpd]":["ikegkuk"],"[Abs][PlUnpd]":["ikegkut"],"[Abs][SgUnpd]":["ikna","ikeggna"],"[Equ][DuUnpd]":["ikegkugcetun"],"[Equ][PlUnpd]":["ikegkucetun"],"[Equ][SgUnpd]":["ik'utun","ikgutun"],"[Loc]":["ikani"],"[Loc][DuUnpd]":["ikegkugni"],"[Loc][PlUnpd]":["ikegkuni"],"[Loc][SgUnpd]":["ikgumi","ik'umi"],"[Rel][DuUnpd]":["ikegkuk"],"[Rel][PlUnpd]":["ikegkut"],"[Rel][SgUnpd]":["ik'um","ikgum"],"[Sec_Ter]":["ikatmun"],"[Ter]":["ikavet"],"[Ter][DuUnpd]":["ikegkugnun"],"[Ter][PlUnpd]":["ikegkunun"],"[Ter][SgUnpd]":["ik'umun","ikgumun"],"[Via]":["ikaggun"],"[Via][DuUnpd]":["ikegkunegnun"],"[Via][PlUnpd]":["ikegkutgun"],"[Via][SgUnpd]":["ikgukun","ik'ukun"],"[Voc][DuUnpd]":["ikegkuuk"],"[Voc][PlUnpd]":["ikegkuut"],"[Voc][SgUnpd]":["iksuuq","ikyuuq","ikeggsuuq","ikeggyuuq"]}},"coming this way":{"extended":{"=i[Encl]":["uka-i"],"[Abl]":["ukaken"],"[Abl_Mod][DuUnpd]":["ukegkugnek"],"[Abl_Mod][PlUnpd]":["ukegkunek"],"[Abl_Mod][SgUnpd]":["uk'umek"],"[Abs][DuUnpd]":["ukegkuk"],"[Abs][PlUnpd]":["ukegkut"],"[Abs][SgUnpd]":["ukna"],"[Equ][DuUnpd]":["ukegkugcetun"],"[Equ][PlUnpd]":["ukegkucetun"],"[Equ][SgUnpd]":["uk'utun"],"[Loc]":["ukani"],"[Loc][DuUnpd]":["ukegkugni"],"[Loc][PlUnpd]":["ukegkuni"],"[Loc][SgUnpd]":["uk'umi"],"[Rel][DuUnpd]":["ukegkuk"],"[Rel][PlUnpd]":["ukegkut"],"[Rel][SgUnpd]":["uk'um"],"[Sec_Ter]":["ukatmun"],"[Ter]":["ukavet"],"[Ter][DuUnpd]":["ukegkugnun"],"[Ter][PlUnpd]":["ukegkunun"],"[Ter][SgUnpd]":["uk'umun"],"[Via]":["ukaggun"],"[Via][DuUnpd]":["ukegkunegnun"],"[Via][PlUnpd]":["ukegkutgun"],"[Via][SgUnpd]":["uk'ukun"],"[Voc][DuUnpd]":["ukegkuuk"],"[Voc][PlUnpd]":["ukegkuut"],"[Voc][SgUnpd]":["ukyuuq","uksuuq"]}},"down below or down the slope":{"extended":{"=i[Encl]":["una-i"],"[Abl]":["unaken"],"[Abl_Mod][DuUnpd]":["unkugnek"],"[Abl_Mod][PlUnpd]":["unkunek"],"[Abl_Mod][SgUnpd]":["un'umek"],"[Abs][DuUnpd]":["unkuk"],"[Abs][PlUnpd]":["unkut"],"[Abs][SgUnpd]":["un'a"],"[Equ][DuUnpd]":["unkugcetun"],"[Equ][PlUnpd]":["unkucetun"],"[Equ][SgUnpd]":["un'utun"],"[Loc]":["unani"],"[Loc][DuUnpd]":["unkugni"],"[Loc][PlUnpd]":["unkuni"],"[Loc][SgUnpd]":["un'umi"],"[Rel][DuUnpd]":["unkuk"],"[Rel][PlUnpd]":["unkut"],"[Rel][SgUnpd]":["un'um"],"[Sec_Ter]":["unatmun"],"[Ter]":["unavet"],"[Ter][DuUnpd]":["unkugnun"],"[Ter][PlUnpd]":["unkunun"],"[Ter][SgUnpd]":["un'umun"],"[Via]":["unaggun"],"[Via][DuUnpd]":["unkunegnun"],"[Via][PlUnpd]":["unkutgun"],"[Via][SgUnpd]":["un'ukun"],"[Voc][DuUnpd]":["unkuuk"],"[Voc][PlUnpd]":["unkuut"],"[Voc][SgUnpd]":["unsuuq","unyuuq"]},"obscured":{"=i[Encl]":["cama-i"],"[Abl]":["camaken"],"[Abl_Mod][DuUnpd]":["camkugnek"],"[Abl_Mod][PlUnpd]":["camkunek"],"[Abl_Mod][SgUnpd]":["cam'umek"],"[Abs][DuUnpd]":["camkuk"],"[Abs][PlUnpd]":["camkut"],"[Abs][SgUnpd]":["camna"],"[Equ][DuUnpd]":["camkugcetun"],"[Equ][PlUnpd]":["camkucetun"],"[Equ][SgUnpd]":["cam'utun"],"[Loc]":["camani"],"[Loc][DuUnpd]":["camkugni"],"[Loc][PlUnpd]":["camkuni"],"[Loc][SgUnpd]":["cam'umi"],"[Rel][DuUnpd]":["camkuk"],"[Rel][PlUnpd]":["camkut"],"[Rel][SgUnpd]":["cam'um"],"[Sec_Ter]":["-"],"[Ter]":["camavet"],"[Ter][DuUnpd]":["camkugnun"],"[Ter][PlUnpd]":["camkunun"],"[Ter][SgUnpd]":["cam'umun"],"[Via]":["camaggun"],"[Via][DuUnpd]":["camkunegnun"],"[Via][PlUnpd]":["camkutgun"],"[Via][SgUnpd]":["cam'ukun"],"[Voc][DuUnpd]":["camkuuk"],"[Voc][PlUnpd]":["camkuut"],"[Voc][SgUnpd]":["camyuuq","camsuuq"]},"restricted":{"=i[Encl]":["kana-i"],"[Abl]":["kanaken"],"[Abl_Mod][DuUnpd]":["kankugnek"],"[Abl_Mod][PlUnpd]":["kankunek"],"[Abl_Mod][SgUnpd]":["kat'umek"],"[Abs][DuUnpd]":["kankuk"],"[Abs][PlUnpd]":["kankut"],"[Abs][SgUnpd]":["kan'a"],"[Equ][DuUnpd]":["kankugcetun"],"[Equ][PlUnpd]":["kankucetun"],"[Equ][SgUnpd]":["kat'utun"],"[Loc]":["kanani"],"[Loc][DuUnpd]":["kankugni"],"[Loc][PlUnpd]":["kankuni"],"[Loc][SgUnpd]":["kat'umi"],"[Rel][DuUnpd]":["kankuk"],"[Rel][PlUnpd]":["kankut"],"[Rel][SgUnpd]":["kat'um"],"[Sec_Ter]":["kanatmun"],"[Ter]":["kanavet"],"[Ter][DuUnpd]":["kankugnun"],"[Ter][PlUnpd]":["kankunun"],"[Ter][SgUnpd]":["kat'umun"],"[Via]":["kanaggun"],"[Via][DuUnpd]":["kankunegnun"],"[Via][PlUnpd]":["kankutgun"],"[Via][SgUnpd]":["kat'ukun"],"[Voc][DuUnpd]":["kankuuk"],"[Voc][PlUnpd]":["kankuut"],"[Voc][SgUnpd]":["kacuuq"]}},"downriver or near the exit":{"extended":{"=i[Encl]":["un'ga-i","un'gaa-i"],"[Abl]":["un'gaken","un'gaaken"],"[Abl_Mod][DuUnpd]":["unegkugnek"],"[Abl_Mod][PlUnpd]":["unegkunek"],"[Abl_Mod][SgUnpd]":["ung'umek"],"[Abs][DuUnpd]":["unegkuk"],"[Abs][PlUnpd]":["unegkut"],"[Abs][SgUnpd]":["unegna"],"[Equ][DuUnpd]":["unegkugcetun"],"[Equ][PlUnpd]":["unegkucetun"],"[Equ][SgUnpd]":["ung'utun"],"[Loc]":["un'gaani","un'gani"],"[Loc][DuUnpd]":["unegkugni"],"[Loc][PlUnpd]":["unegkuni"],"[Loc][SgUnpd]":["ung'umi"],"[Rel][DuUnpd]":["unegkuk"],"[Rel][PlUnpd]":["unegkut"],"[Rel][SgUnpd]":["ung'um"],"[Sec_Ter]":["un'gatmun","un'gaatmun"],"[Ter]":["un'gaavet","un'gavet"],"[Ter][DuUnpd]":["unegkugnun"],"[Ter][PlUnpd]":["unegkunun"],"[Ter][SgUnpd]":["ung'umun"],"[Via]":["un'gaggun","un'gaaggun"],"[Via][DuUnpd]":["unegkunegnun"],"[Via][PlUnpd]":["unegkutgun"],"[Via][SgUnpd]":["ung'ukun"],"[Voc][DuUnpd]":["unegkuuk"],"[Voc][PlUnpd]":["unegkuut"],"[Voc][SgUnpd]":["unegyuuq","unegsuuq"]},"obscured":{"=i[Encl]":["cakma-i"],"[Abl]":["cakmaken"],"[Abl_Mod][DuUnpd]":["cakemkugnek"],"[Abl_Mod][PlUnpd]":["cakemkunek"],"[Abl_Mod][SgUnpd]":["cak'mumek"],"[Abs][DuUnpd]":["cakemkuk"],"[Abs][PlUnpd]":["cakemkut"],"[Abs][SgUnpd]":["cakemna"],"[Equ][DuUnpd]":["cakemkugcetun"],"[Equ][PlUnpd]":["cakemkucetun"],"[Equ][SgUnpd]":["cak'mutun"],"[Loc]":["cakmani"],"[Loc][DuUnpd]":["cakemkugni"],"[Loc][PlUnpd]":["cakemkuni"],"[Loc][SgUnpd]":["cak'mumi"],"[Rel][DuUnpd]":["cakemkuk"],"[Rel][PlUnpd]":["cakemkut"],"[Rel][SgUnpd]":["cak'mum"],"[Sec_Ter]":["-"],"[Ter]":["cakmavet"],"[Ter][DuUnpd]":["cakemkugnun"],"[Ter][PlUnpd]":["cakemkunun"],"[Ter][SgUnpd]":["cak'mumun"],"[Via]":["cakmaggun"],"[Via][DuUnpd]":["cakemkunegnun"],"[Via][PlUnpd]":["cakemkutgun"],"[Via][SgUnpd]":["cak'mukun"],"[Voc][DuUnpd]":["cakemkuuk"],"[Voc][PlUnpd]":["cakemkuut"],"[Voc][SgUnpd]":["cakemsuuq","cakemyuuq"]},"restricted":{"=i[Encl]":["ua-i"],"[Abl]":["uaken"],"[Abl_Mod][DuUnpd]":["ugkugnek"],"[Abl_Mod][PlUnpd]":["ugkunek"],"[Abl_Mod][SgUnpd]":["ug'umek"],"[Abs][DuUnpd]":["ugkuk"],"[Abs][PlUnpd]":["ugkut"],"[Abs][SgUnpd]":["ugna"],"[Equ][DuUnpd]":["ugkugcetun"],"[Equ][PlUnpd]":["ugkucetun"],"[Equ][SgUnpd]":["ug'utun"],"[Loc]":["uani"],"[Loc][DuUnpd]":["ugkugni"],"[Loc][PlUnpd]":["ugkuni"],"[Loc][SgUnpd]":["ug'umi"],"[Rel][DuUnpd]":["ugkuk"],"[Rel][PlUnpd]":["ugkut"],"[Rel][SgUnpd]":["ug'um"],"[Sec_Ter]":["uatmun"],"[Ter]":["uavet"],"[Ter][DuUnpd]":["ugkugnun"],"[Ter][PlUnpd]":["ugkunun"],"[Ter][SgUnpd]":["ug'umun"],"[Via]":["uaggun"],"[Via][DuUnpd]":["ugkunegnun"],"[Via][PlUnpd]":["ugkutgun"],"[Via][SgUnpd]":["ug'ukun"],"[Voc][DuUnpd]":["ugkuuk"],"[Voc][PlUnpd]":["ugkuut"],"[Voc][SgUnpd]":["ugsuuq","ugyuuq"]}},"here, near speaker":{"extended":{"=i[Encl]":["maa-i"],"[Abl]":["maaken"],"[Abl_Mod][DuUnpd]":["makugnek"],"[Abl_Mod][PlUnpd]":["makunek"],"[Abl_Mod][SgUnpd]":["mat'umek"],"[Abs][DuUnpd]":["makuk"],"[Abs][PlUnpd]":["makut"],"[Abs][SgUnpd]":["man'a"],"[Equ][DuUnpd]":["makugcetun"],"[Equ][PlUnpd]":["makucetun"],"[Equ][SgUnpd]":["mat'utun"],"[Loc]":["maani"],"[Loc][DuUnpd]":["makugni"],"[Loc][PlUnpd]":["makuni"],"[Loc][SgUnpd]":["mat'umi"],"[Rel][DuUnpd]":["makuk"],"[Rel][PlUnpd]":["makut"],"[Rel][SgUnpd]":["mat'um"],"[Sec_Ter]":["maatmun"],"[Ter]":["maavet"],"[Ter][DuUnpd]":["makugnun"],"[Ter][PlUnpd]":["makunun"],"[Ter][SgUnpd]":["mat'umun"],"[Via]":["maaggun"],"[Via][DuUnpd]":["makunegnun"],"[Via][PlUnpd]":["makutgun"],"[Via][SgUnpd]":["mat'ukun"],"[Voc][DuUnpd]":["makuuk"],"[Voc][PlUnpd]":["makuut"],"[Voc][SgUnpd]":["macuuq"]},"obscured":{"=i[Encl]":["ima-i"],"[Abl]":["imaken"],"[Abl_Mod][DuUnpd]":["imkugnek"],"[Abl_Mod][PlUnpd]":["imkunek"],"[Abl_Mod][SgUnpd]":["im'umek","imumek"],"[Abs][DuUnpd]":["imkuk"],"[Abs][PlUnpd]":["imkut"],"[Abs][SgUnpd]":["imna"],"[Equ][DuUnpd]":["imkugcetun"],"[Equ][PlUnpd]":["imkucetun"],"[Equ][SgUnpd]":["im'utun","imutun"],"[Loc]":["imani"],"[Loc][DuUnpd]":["imkugni"],"[Loc][PlUnpd]":["imkuni"],"[Loc][SgUnpd]":["im'umi","imumi"],"[Rel][DuUnpd]":["imkuk"],"[Rel][PlUnpd]":["imkut"],"[Rel][SgUnpd]":["imum","im'um"],"[Sec_Ter]":["-"],"[Ter]":["imavet"],"[Ter][DuUnpd]":["imkugnun"],"[Ter][PlUnpd]":["imkunun"],"[Ter][SgUnpd]":["im'umun","imumun"],"[Via]":["imaggun"],"[Via][DuUnpd]":["imkunegnun"],"[Via][PlUnpd]":["imkutgun"],"[Via][SgUnpd]":["imukun","im'ukun"],"[Voc][DuUnpd]":["imkuuk"],"[Voc][PlUnpd]":["imkuut"],"[Voc][SgUnpd]":["imsuuq","imyuuq"]},"restricted":{"=i[Encl]":["wa-i"],"[Abl]":["waken"],"[Abl_Mod][DuUnpd]":["ukugnek"],"[Abl_Mod][PlUnpd]":["ukunek"],"[Abl_Mod][SgUnpd]":["uumek"],"[Abs][DuUnpd]":["ukuk"],"[Abs][PlUnpd]":["ukut"],"[Abs][SgUnpd]":["una"],"[Equ][DuUnpd]":["ukugcetun"],"[Equ][PlUnpd]":["ukucetun"],"[Equ][SgUnpd]":["uutun"],"[Loc]":["wani"],"[Loc][DuUnpd]":["ukugni"],"[Loc][PlUnpd]":["ukuni"],"[Loc][SgUnpd]":["uumi"],"[Rel][DuUnpd]":["ukuk"],"[Rel][PlUnpd]":["ukut"],"[Rel][SgUnpd]":["uum"],"[Sec_Ter]":["-"],"[Ter]":["wavet"],"[Ter][DuUnpd]":["ukugnun"],"[Ter][PlUnpd]":["ukunun"],"[Ter][SgUnpd]":["uumun"],"[Via]":["waggun","uuggun"],"[Via][DuUnpd]":["ukunegnun"],"[Via][PlUnpd]":["ukutgun"],"[Via][SgUnpd]":["uukun","uuggun"],"[Voc][DuUnpd]":["ukuuk"],"[Voc][PlUnpd]":["ukuut"],"[Voc][SgUnpd]":["usuuq","uyuuq"]}},"inside, inland, or upriver":{"extended":{"=i[Encl]":["qava-i"],"[Abl]":["qavaken"],"[Abl_Mod][DuUnpd]":["qaugkugnek","qau\u0361gkugnek"],"[Abl_Mod][PlUnpd]":["qaugkunek","qau\u0361gkunek"],"[Abl_Mod][SgUnpd]":["qau\u0361g'umek","qaug'umek"],"[Abs][DuUnpd]":["qaugkuk","qau\u0361gkuk"],"[Abs][PlUnpd]":["qau\u0361gkut","qaugkut"],"[Abs][SgUnpd]":["qaugna","qau\u0361gna"],"[Equ][DuUnpd]":["qaugkugcetun","qau\u0361gkugcetun"],"[Equ][PlUnpd]":["qau\u0361gkucetun","qaugkucetun"],"[Equ][SgUnpd]":["qau\u0361g'utun","qaug'utun"],"[Loc]":["qavani"],"[Loc][DuUnpd]":["qaugkugni","qau\u0361gkugni"],"[Loc][PlUnpd]":["qau\u0361gkuni","qaugkuni"],"[Loc][SgUnpd]":["qaug'umi","qau\u0361g'umi"],"[Rel][DuUnpd]":["qaugkuk","qau\u0361gkuk"],"[Rel][PlUnpd]":["qau\u0361gkut","qaugkut"],"[Rel][SgUnpd]":["qaug'um","qau\u0361g'um"],"[Sec_Ter]":["qavatmun"],"[Ter]":["qavavet"],"[Ter][DuUnpd]":["qaugkugnun","qau\u0361gkugnun"],"[Ter][PlUnpd]":["qau\u0361gkunun","qaugkunun"],"[Ter][SgUnpd]":["qaug'umun","qau\u0361g'umun"],"[Via]":["qavaggun"],"[Via][DuUnpd]":["qaugkunegnun","qau\u0361gkunegnun"],"[Via][PlUnpd]":["qau\u0361gkutgun","qaugkutgun"],"[Via][SgUnpd]":["qaug'ukun","qau\u0361g'ukun"],"[Voc][DuUnpd]":["qaugkuuk","qau\u0361gkuuk"],"[Voc][PlUnpd]":["qau\u0361gkuut","qaugkuut"],"[Voc][SgUnpd]":["qaugyuuq","qaugsuuq","qau\u0361gyuuq","qau\u0361gsuuq"]},"obscured":{"=i[Encl]":["qama-i"],"[Abl]":["qamaken"],"[Abl_Mod][DuUnpd]":["qamkugnek"],"[Abl_Mod][PlUnpd]":["qamkunek"],"[Abl_Mod][SgUnpd]":["qam'umek"],"[Abs][DuUnpd]":["qamkuk"],"[Abs][PlUnpd]":["qamkut"],"[Abs][SgUnpd]":["qamna"],"[Equ][DuUnpd]":["qamkugcetun"],"[Equ][PlUnpd]":["qamkucetun"],"[Equ][SgUnpd]":["qam'utun"],"[Loc]":["qamani"],"[Loc][DuUnpd]":["qamkugni"],"[Loc][PlUnpd]":["qamkuni"],"[Loc][SgUnpd]":["qam'umi"],"[Rel][DuUnpd]":["qamkuk"],"[Rel][PlUnpd]":["qamkut"],"[Rel][SgUnpd]":["qam'um"],"[Sec_Ter]":["-"],"[Ter]":["qamavet"],"[Ter][DuUnpd]":["qamkugnun"],"[Ter][PlUnpd]":["qamkunun"],"[Ter][SgUnpd]":["qam'umun"],"[Via]":["qamaggun"],"[Via][DuUnpd]":["qamkunegnun"],"[Via][PlUnpd]":["qamkutgun"],"[Via][SgUnpd]":["qam'ukun"],"[Voc][DuUnpd]":["qamkuuk"],"[Voc][PlUnpd]":["qamkuut"],"[Voc][SgUnpd]":["qamsuuq","qamyuuq"]},"restricted":{"=i[Encl]":["kia-i"],"[Abl]":["kiaken"],"[Abl_Mod][DuUnpd]":["kiu\u0361gkugnek","kiugkugnek"],"[Abl_Mod][PlUnpd]":["kiugkunek","kiu\u0361gkunek"],"[Abl_Mod][SgUnpd]":["kiugumek","kiug'umek","kiu\u0361g'umek"],"[Abs][DuUnpd]":["kiu\u0361gkuk","kiugkuk"],"[Abs][PlUnpd]":["kiugkut","kiu\u0361gkut"],"[Abs][SgUnpd]":["kiugna","kiu\u0361gna"],"[Equ][DuUnpd]":["kiu\u0361gkugcetun","kiugkugcetun"],"[Equ][PlUnpd]":["kiugkucetun","kiu\u0361gkucetun"],"[Equ][SgUnpd]":["kiugutun","kiug'utun","kiu\u0361g'utun"],"[Loc]":["kiani"],"[Loc][DuUnpd]":["kiu\u0361gkugni","kiugkugni"],"[Loc][PlUnpd]":["kiugkuni","kiu\u0361gkuni"],"[Loc][SgUnpd]":["kiu\u0361g'umi","kiug'umi","kiugumi"],"[Rel][DuUnpd]":["kiu\u0361gkuk","kiugkuk"],"[Rel][PlUnpd]":["kiugkut","kiu\u0361gkut"],"[Rel][SgUnpd]":["kiu\u0361g'um","kiugum","kiug'um"],"[Sec_Ter]":["kiatmun"],"[Ter]":["kiavet"],"[Ter][DuUnpd]":["kiugkugnun","kiu\u0361gkugnun"],"[Ter][PlUnpd]":["kiu\u0361gkunun","kiugkunun"],"[Ter][SgUnpd]":["kiug'umun","kiu\u0361g'umun","kiugumun"],"[Via]":["kiaggun"],"[Via][DuUnpd]":["kiu\u0361gkunegnun","kiugkunegnun"],"[Via][PlUnpd]":["kiugkutgun","kiu\u0361gkutgun"],"[Via][SgUnpd]":["kiug'ukun","kiugukun","kiu\u0361g'ukun"],"[Voc][DuUnpd]":["kiugkuuk","kiu\u0361gkuuk"],"[Voc][PlUnpd]":["kiu\u0361gkuut","kiugkuut"],"[Voc][SgUnpd]":["kiugsuuq","kiu\u0361gyuuq","kiu\u0361gsuuq","kiugyuuq"]}},"outside":{"extended":{"=i[Encl]":["qii-i","qagaa-i"],"[Abl]":["qiiken","qagaaken"],"[Abl_Mod][DuUnpd]":["qagkugnek"],"[Abl_Mod][PlUnpd]":["qagkunek"],"[Abl_Mod][SgUnpd]":["qag'umek"],"[Abs][DuUnpd]":["qagkuk"],"[Abs][PlUnpd]":["qagkut"],"[Abs][SgUnpd]":["qagna"],"[Equ][DuUnpd]":["qagkugcetun"],"[Equ][PlUnpd]":["qagkucetun"],"[Equ][SgUnpd]":["qag'utun"],"[Loc]":["qiini","qagaani"],"[Loc][DuUnpd]":["qagkugni"],"[Loc][PlUnpd]":["qagkuni"],"[Loc][SgUnpd]":["qag'umi"],"[Rel][DuUnpd]":["qagkuk"],"[Rel][PlUnpd]":["qagkut"],"[Rel][SgUnpd]":["qag'um"],"[Sec_Ter]":["qagaatmun","qiitmun"],"[Ter]":["qiivet","qagaavet"],"[Ter][DuUnpd]":["qagkugnun"],"[Ter][PlUnpd]":["qagkunun"],"[Ter][SgUnpd]":["qag'umun"],"[Via]":["qiiggun","qagaaggun"],"[Via][DuUnpd]":["qagkunegnun"],"[Via][PlUnpd]":["qagkutgun"],"[Via][SgUnpd]":["qag'ukun"],"[Voc][DuUnpd]":["qagkuuk"],"[Voc][PlUnpd]":["qagkuut"],"[Voc][SgUnpd]":["qagyuuq","qagsuuq"]},"obscured":{"=i[Encl]":["qakma-i"],"[Abl]":["qakmaken"],"[Abl_Mod][DuUnpd]":["qakemkugnek"],"[Abl_Mod][PlUnpd]":["qakemkunek"],"[Abl_Mod][SgUnpd]":["qak'mumek"],"[Abs][DuUnpd]":["qakemkuk"],"[Abs][PlUnpd]":["qakemkut"],"[Abs][SgUnpd]":["qakemna"],"[Equ][DuUnpd]":["qakemkugcetun"],"[Equ][PlUnpd]":["qakemkucetun"],"[Equ][SgUnpd]":["qak'mutun"],"[Loc]":["qakmani"],"[Loc][DuUnpd]":["qakemkugni"],"[Loc][PlUnpd]":["qakemkuni"],"[Loc][SgUnpd]":["qak'mumi"],"[Rel][DuUnpd]":["qakemkuk"],"[Rel][PlUnpd]":["qakemkut"],"[Rel][SgUnpd]":["qak'mum"],"[Sec_Ter]":["-"],"[Ter]":["qakmavet"],"[Ter][DuUnpd]":["qakemkugnun"],"[Ter][PlUnpd]":["qakemkunun"],"[Ter][SgUnpd]":["qak'mumun"],"[Via]":["qakmaggun"],"[Via][DuUnpd]":["qakemkunegnun"],"[Via][PlUnpd]":["qakemkutgun"],"[Via][SgUnpd]":["qak'mukun"],"[Voc][DuUnpd]":["qakemkuuk"],"[Voc][PlUnpd]":["qakemkuut"],"[Voc][SgUnpd]":["qakemyuuq","qakemsuuq"]},"restricted":{"=i[Encl]":["kegga-i"],"[Abl]":["keggaken"],"[Abl_Mod][DuUnpd]":["kegkugnek"],"[Abl_Mod][PlUnpd]":["kegkunek"],"[Abl_Mod][SgUnpd]":["kegg'umek"],"[Abs][DuUnpd]":["kegkuk"],"[Abs][PlUnpd]":["kegkut"],"[Abs][SgUnpd]":["keggna"],"[Equ][DuUnpd]":["kegkugcetun"],"[Equ][PlUnpd]":["kegkucetun"],"[Equ][SgUnpd]":["kegg'utun"],"[Loc]":["keggani"],"[Loc][DuUnpd]":["kegkugni"],"[Loc][PlUnpd]":["kegkuni"],"[Loc][SgUnpd]":["kegg'umi"],"[Rel][DuUnpd]":["kegkuk"],"[Rel][PlUnpd]":["kegkut"],"[Rel][SgUnpd]":["kegg'um"],"[Sec_Ter]":["keggatmun"],"[Ter]":["keggavet"],"[Ter][DuUnpd]":["kegkugnun"],"[Ter][PlUnpd]":["kegkunun"],"[Ter][SgUnpd]":["kegg'umun"],"[Via]":["keggaggun"],"[Via][DuUnpd]":["kegkunegnun"],"[Via][PlUnpd]":["kegkutgun"],"[Via][SgUnpd]":["kegg'ukun"],"[Voc][DuUnpd]":["kegkuuk"],"[Voc][PlUnpd]":["kegkuut"],"[Voc][SgUnpd]":["keggyuuq","keggsuuq"]}},"over there or going away":{"extended":{"=i[Encl]":["ava-i"],"[Abl]":["avaken"],"[Abl_Mod][DuUnpd]":["augkugnek","au\u0361gkugnek","awkugnek"],"[Abl_Mod][PlUnpd]":["augkunek","au\u0361gkunek","awkunek"],"[Abl_Mod][SgUnpd]":["aug'umek","au\u0361g'umek"],"[Abs][DuUnpd]":["augkuk","au\u0361gkuk","awkuk"],"[Abs][PlUnpd]":["awkut","augkut","au\u0361gkut"],"[Abs][SgUnpd]":["augna","au\u0361gna"],"[Equ][DuUnpd]":["augkugcetun","awkugcetun","au\u0361gkugcetun"],"[Equ][PlUnpd]":["awkucetun","augkucetun","au\u0361gkucetun"],"[Equ][SgUnpd]":["aug'utun","au\u0361g'utun"],"[Loc]":["avani"],"[Loc][DuUnpd]":["au\u0361gkugni","augkugni","awkugni"],"[Loc][PlUnpd]":["awkuni","augkuni","au\u0361gkuni"],"[Loc][SgUnpd]":["au\u0361g'umi","aug'umi"],"[Rel][DuUnpd]":["augkuk","au\u0361gkuk","awkuk"],"[Rel][PlUnpd]":["awkut","augkut","au\u0361gkut"],"[Rel][SgUnpd]":["aug'um","au\u0361g'um"],"[Sec_Ter]":["avatmun"],"[Ter]":["avavet"],"[Ter][DuUnpd]":["au\u0361gkugnun","awkugnun","augkugnun"],"[Ter][PlUnpd]":["awkunun","au\u0361gkunun","augkunun"],"[Ter][SgUnpd]":["aug'umun","au\u0361g'umun"],"[Via]":["avaggun"],"[Via][DuUnpd]":["au\u0361gkunegnun","augkunegnun","awkunegnun"],"[Via][PlUnpd]":["awkutgun","augkutgun","au\u0361gkutgun"],"[Via][SgUnpd]":["aug'ukun","au\u0361g'ukun"],"[Voc][DuUnpd]":["augkuuk","au\u0361gkuuk","awkuuk"],"[Voc][PlUnpd]":["awkuut","augkuut","au\u0361gkuut"],"[Voc][SgUnpd]":["au\u0361gyuuq","au\u0361gsuuq","augyuuq","augsuuq"]},"obscured":{"=i[Encl]":["ama-i"],"[Abl]":["amaken"],"[Abl_Mod][DuUnpd]":["amkugnek"],"[Abl_Mod][PlUnpd]":["amkunek"],"[Abl_Mod][SgUnpd]":["am'umek"],"[Abs][DuUnpd]":["amkuk"],"[Abs][PlUnpd]":["amkut"],"[Abs][SgUnpd]":["amna"],"[Equ][DuUnpd]":["amkugcetun"],"[Equ][PlUnpd]":["amkucetun"],"[Equ][SgUnpd]":["am'utun"],"[Loc]":["amani"],"[Loc][DuUnpd]":["amkugni"],"[Loc][PlUnpd]":["amkuni"],"[Loc][SgUnpd]":["am'umi"],"[Rel][DuUnpd]":["amkuk"],"[Rel][PlUnpd]":["amkut"],"[Rel][SgUnpd]":["am'um"],"[Sec_Ter]":["-"],"[Ter]":["amavet"],"[Ter][DuUnpd]":["amkugnun"],"[Ter][PlUnpd]":["amkunun"],"[Ter][SgUnpd]":["am'umun"],"[Via]":["amaggun"],"[Via][DuUnpd]":["amkunegnun"],"[Via][PlUnpd]":["amkutgun"],"[Via][SgUnpd]":["am'ukun"],"[Voc][DuUnpd]":["amkuuk"],"[Voc][PlUnpd]":["amkuut"],"[Voc][SgUnpd]":["amsuuq","amyuuq"]},"restricted":{"=i[Encl]":["yaa-i"],"[Abl]":["yaaken"],"[Abl_Mod][DuUnpd]":["ingkugnek"],"[Abl_Mod][PlUnpd]":["ingkunek"],"[Abl_Mod][SgUnpd]":["ing'umek"],"[Abs][DuUnpd]":["ingkuk"],"[Abs][PlUnpd]":["ingkut"],"[Abs][SgUnpd]":["ingna"],"[Equ][DuUnpd]":["ingkugcetun"],"[Equ][PlUnpd]":["ingkucetun"],"[Equ][SgUnpd]":["ing'utun"],"[Loc]":["yaani"],"[Loc][DuUnpd]":["ingkugni"],"[Loc][PlUnpd]":["ingkuni"],"[Loc][SgUnpd]":["ing'umi"],"[Rel][DuUnpd]":["ingkuk"],"[Rel][PlUnpd]":["ingkut"],"[Rel][SgUnpd]":["ing'um"],"[Sec_Ter]":["yaatmun"],"[Ter]":["yaavet"],"[Ter][DuUnpd]":["ingkugnun"],"[Ter][PlUnpd]":["ingkunun"],"[Ter][SgUnpd]":["ing'umun"],"[Via]":["yaaggun"],"[Via][DuUnpd]":["ingkunegnun"],"[Via][PlUnpd]":["ingkutgun"],"[Via][SgUnpd]":["ing'ukun"],"[Voc][DuUnpd]":["ingkuuk"],"[Voc][PlUnpd]":["ingkuut"],"[Voc][SgUnpd]":["ingyuuq","ingsuuq"]}},"there, near listener or in context":{"extended":{"=i[Encl]":["tamaa-i"],"[Abl]":["tamaaken"],"[Abl_Mod][DuUnpd]":["tamakugnek"],"[Abl_Mod][PlUnpd]":["tamakunek"],"[Abl_Mod][SgUnpd]":["tamatumek"],"[Abs][DuUnpd]":["tamakuk"],"[Abs][PlUnpd]":["tamakut"],"[Abs][SgUnpd]":["tamana"],"[Equ][DuUnpd]":["tamakugcetun"],"[Equ][PlUnpd]":["tamakucetun"],"[Equ][SgUnpd]":["tamatutun"],"[Loc]":["tamaani"],"[Loc][DuUnpd]":["tamakugni"],"[Loc][PlUnpd]":["tamakuni"],"[Loc][SgUnpd]":["tamatumi"],"[Rel][DuUnpd]":["tamakuk"],"[Rel][PlUnpd]":["tamakut"],"[Rel][SgUnpd]":["tamatum"],"[Sec_Ter]":["tamaatmun"],"[Ter]":["tamaavet"],"[Ter][DuUnpd]":["tamakugnun"],"[Ter][PlUnpd]":["tamakunun"],"[Ter][SgUnpd]":["tamatumun"],"[Via]":["tamaaggun"],"[Via][DuUnpd]":["tamakunegnun"],"[Via][PlUnpd]":["tamakutgun"],"[Via][SgUnpd]":["tamatukun"],"[Voc][DuUnpd]":["tamakuuk"],"[Voc][PlUnpd]":["tamakuut"],"[Voc][SgUnpd]":["tamasuuq","tamayuuq"]},"restricted":{"=i[Encl]":["tua-i","tava-i"],"[Abl]":["tavaken","tuaken"],"[Abl_Mod][DuUnpd]":["taukugnek"],"[Abl_Mod][PlUnpd]":["taukunek"],"[Abl_Mod][SgUnpd]":["taumek"],"[Abs][DuUnpd]":["taukuk"],"[Abs][PlUnpd]":["taukut"],"[Abs][SgUnpd]":["tauna"],"[Equ][DuUnpd]":["taukugcetun"],"[Equ][PlUnpd]":["taukucetun"],"[Equ][SgUnpd]":["tautun"],"[Loc]":["tavani","tuani"],"[Loc][DuUnpd]":["taukugni"],"[Loc][PlUnpd]":["taukuni"],"[Loc][SgUnpd]":["taumi"],"[Rel][DuUnpd]":["taukuk"],"[Rel][PlUnpd]":["taukut"],"[Rel][SgUnpd]":["taum"],"[Sec_Ter]":["-"],"[Ter]":["tavavet","tuavet"],"[Ter][DuUnpd]":["taukugnun"],"[Ter][PlUnpd]":["taukunun"],"[Ter][SgUnpd]":["taumun"],"[Via]":["tavaggun","tuaggun"],"[Via][DuUnpd]":["taukunegnun"],"[Via][PlUnpd]":["taukutgun"],"[Via][SgUnpd]":["taukun"],"[Voc][DuUnpd]":["taukuuk"],"[Voc][PlUnpd]":["taukuut"],"[Voc][SgUnpd]":["tausuuq","tauyuuq"]}},"up above":{"extended":{"=i[Encl]":["pagaa-i","pii-i"],"[Abl]":["piiken","pagaaken"],"[Abl_Mod][DuUnpd]":["pagkugnek"],"[Abl_Mod][PlUnpd]":["pagkunek"],"[Abl_Mod][SgUnpd]":["pag'umek"],"[Abs][DuUnpd]":["pagkuk"],"[Abs][PlUnpd]":["pagkut"],"[Abs][SgUnpd]":["pagna"],"[Equ][DuUnpd]":["pagkugcetun"],"[Equ][PlUnpd]":["pagkucetun"],"[Equ][SgUnpd]":["pag'utun"],"[Loc]":["piini","pagaani"],"[Loc][DuUnpd]":["pagkugni"],"[Loc][PlUnpd]":["pagkuni"],"[Loc][SgUnpd]":["pag'umi"],"[Rel][DuUnpd]":["pagkuk"],"[Rel][PlUnpd]":["pagkut"],"[Rel][SgUnpd]":["pag'um"],"[Sec_Ter]":["pagaatmun","piitmun"],"[Ter]":["pagaavet","piivet"],"[Ter][DuUnpd]":["pagkugnun"],"[Ter][PlUnpd]":["pagkunun"],"[Ter][SgUnpd]":["pag'umun"],"[Via]":["pagaaggun","piiggun"],"[Via][DuUnpd]":["pagkunegnun"],"[Via][PlUnpd]":["pagkutgun"],"[Via][SgUnpd]":["pag'ukun"],"[Voc][DuUnpd]":["pagkuuk"],"[Voc][PlUnpd]":["pagkuut"],"[Voc][SgUnpd]":["pagsuuq","pagyuuq"]},"obscured":{"=i[Encl]":["pakma-i"],"[Abl]":["pakmaken"],"[Abl_Mod][DuUnpd]":["pakemkugnek"],"[Abl_Mod][PlUnpd]":["pakemkunek"],"[Abl_Mod][SgUnpd]":["pak'mumek"],"[Abs][DuUnpd]":["pakemkuk"],"[Abs][PlUnpd]":["pakemkut"],"[Abs][SgUnpd]":["pakemna"],"[Equ][DuUnpd]":["pakemkugcetun"],"[Equ][PlUnpd]":["pakemkucetun"],"[Equ][SgUnpd]":["pak'mutun"],"[Loc]":["pakmani"],"[Loc][DuUnpd]":["pakemkugni"],"[Loc][PlUnpd]":["pakemkuni"],"[Loc][SgUnpd]":["pak'mumi"],"[Rel][DuUnpd]":["pakemkuk"],"[Rel][PlUnpd]":["pakemkut"],"[Rel][SgUnpd]":["pak'mum"],"[Sec_Ter]":["-"],"[Ter]":["pakmavet"],"[Ter][DuUnpd]":["pakemkugnun"],"[Ter][PlUnpd]":["pakemkunun"],"[Ter][SgUnpd]":["pak'mumun"],"[Via]":["pakmaggun"],"[Via][DuUnpd]":["pakemkunegnun"],"[Via][PlUnpd]":["pakemkutgun"],"[Via][SgUnpd]":["pak'mukun"],"[Voc][DuUnpd]":["pakemkuuk"],"[Voc][PlUnpd]":["pakemkuut"],"[Voc][SgUnpd]":["pakemsuuq","pakemyuuq"]},"restricted":{"=i[Encl]":["pika-i"],"[Abl]":["pikaken"],"[Abl_Mod][DuUnpd]":["pikegkugnek"],"[Abl_Mod][PlUnpd]":["pikegkunek"],"[Abl_Mod][SgUnpd]":["pikgumek","pik'umek"],"[Abs][DuUnpd]":["pikegkuk"],"[Abs][PlUnpd]":["pikegkut"],"[Abs][SgUnpd]":["pikna","pikeggna"],"[Equ][DuUnpd]":["pikegkugcetun"],"[Equ][PlUnpd]":["pikegkucetun"],"[Equ][SgUnpd]":["pikgutun","pik'utun"],"[Loc]":["pikani"],"[Loc][DuUnpd]":["pikegkugni"],"[Loc][PlUnpd]":["pikegkuni"],"[Loc][SgUnpd]":["pikgumi","pik'umi"],"[Rel][DuUnpd]":["pikegkuk"],"[Rel][PlUnpd]":["pikegkut"],"[Rel][SgUnpd]":["pikgum","pik'um"],"[Sec_Ter]":["pikatmun"],"[Ter]":["pikavet"],"[Ter][DuUnpd]":["pikegkugnun"],"[Ter][PlUnpd]":["pikegkunun"],"[Ter][SgUnpd]":["pikgumun","pik'umun"],"[Via]":["pikaggun"],"[Via][DuUnpd]":["pikegkunegnun"],"[Via][PlUnpd]":["pikegkutgun"],"[Via][SgUnpd]":["pik'ukun","pikgukun"],"[Voc][DuUnpd]":["pikegkuuk"],"[Voc][PlUnpd]":["pikegkuut"],"[Voc][SgUnpd]":["pikeggyuuq","pikyuuq","piksuuq","pikeggsuuq"]}},"up the slope":{"extended":{"=i[Encl]":["pava-i"],"[Abl]":["pavaken"],"[Abl_Mod][DuUnpd]":["paugkugnek","pau\u0361gkugnek"],"[Abl_Mod][PlUnpd]":["paugkunek","pau\u0361gkunek"],"[Abl_Mod][SgUnpd]":["paug'umek","pau\u0361g'umek"],"[Abs][DuUnpd]":["paugkuk","pau\u0361gkuk"],"[Abs][PlUnpd]":["paugkut","pau\u0361gkut"],"[Abs][SgUnpd]":["paugna","pau\u0361gna"],"[Equ][DuUnpd]":["paugkugcetun","pau\u0361gkugcetun"],"[Equ][PlUnpd]":["paugkucetun","pau\u0361gkucetun"],"[Equ][SgUnpd]":["paug'utun","pau\u0361g'utun"],"[Loc]":["pavani"],"[Loc][DuUnpd]":["pau\u0361gkugni","paugkugni"],"[Loc][PlUnpd]":["pau\u0361gkuni","paugkuni"],"[Loc][SgUnpd]":["paug'umi","pau\u0361g'umi"],"[Rel][DuUnpd]":["paugkuk","pau\u0361gkuk"],"[Rel][PlUnpd]":["paugkut","pau\u0361gkut"],"[Rel][SgUnpd]":["paug'um","pau\u0361g'um"],"[Sec_Ter]":["pavatmun"],"[Ter]":["pavavet"],"[Ter][DuUnpd]":["pau\u0361gkugnun","paugkugnun"],"[Ter][PlUnpd]":["paugkunun","pau\u0361gkunun"],"[Ter][SgUnpd]":["paug'umun","pau\u0361g'umun"],"[Via]":["pavaggun"],"[Via][DuUnpd]":["pau\u0361gkunegnun","paugkunegnun"],"[Via][PlUnpd]":["paugkutgun","pau\u0361gkutgun"],"[Via][SgUnpd]":["paug'ukun","pau\u0361g'ukun"],"[Voc][DuUnpd]":["paugkuuk","pau\u0361gkuuk"],"[Voc][PlUnpd]":["paugkuut","pau\u0361gkuut"],"[Voc][SgUnpd]":["pau\u0361gyuuq","pau\u0361gsuuq","paugyuuq","paugsuuq"]},"obscured":{"=i[Encl]":["pama-i"],"[Abl]":["pamaken"],"[Abl_Mod][DuUnpd]":["pamkugnek"],"[Abl_Mod][PlUnpd]":["pamkunek"],"[Abl_Mod][SgUnpd]":["pam'umek"],"[Abs][DuUnpd]":["pamkuk"],"[Abs][PlUnpd]":["pamkut"],"[Abs][SgUnpd]":["pamna"],"[Equ][DuUnpd]":["pamkugcetun"],"[Equ][PlUnpd]":["pamkucetun"],"[Equ][SgUnpd]":["pam'utun"],"[Loc]":["pamani"],"[Loc][DuUnpd]":["pamkugni"],"[Loc][PlUnpd]":["pamkuni"],"[Loc][SgUnpd]":["pam'umi"],"[Rel][DuUnpd]":["pamkuk"],"[Rel][PlUnpd]":["pamkut"],"[Rel][SgUnpd]":["pam'um"],"[Sec_Ter]":["-"],"[Ter]":["pamavet"],"[Ter][DuUnpd]":["pamkugnun"],"[Ter][PlUnpd]":["pamkunun"],"[Ter][SgUnpd]":["pam'umun"],"[Via]":["pamaggun"],"[Via][DuUnpd]":["pamkunegnun"],"[Via][PlUnpd]":["pamkutgun"],"[Via][SgUnpd]":["pam'ukun"],"[Voc][DuUnpd]":["pamkuuk"],"[Voc][PlUnpd]":["pamkuut"],"[Voc][SgUnpd]":["pamyuuq","pamsuuq"]},"restricted":{"=i[Encl]":["pia-i"],"[Abl]":["piaken"],"[Abl_Mod][DuUnpd]":["pingkugnek"],"[Abl_Mod][PlUnpd]":["pingkunek"],"[Abl_Mod][SgUnpd]":["ping'umek"],"[Abs][DuUnpd]":["pingkuk"],"[Abs][PlUnpd]":["pingkut"],"[Abs][SgUnpd]":["pingna"],"[Equ][DuUnpd]":["pingkugcetun"],"[Equ][PlUnpd]":["pingkucetun"],"[Equ][SgUnpd]":["ping'utun"],"[Loc]":["piani"],"[Loc][DuUnpd]":["pingkugni"],"[Loc][PlUnpd]":["pingkuni"],"[Loc][SgUnpd]":["ping'umi"],"[Rel][DuUnpd]":["pingkuk"],"[Rel][PlUnpd]":["pingkut"],"[Rel][SgUnpd]":["ping'um"],"[Sec_Ter]":["piatmun"],"[Ter]":["piavet"],"[Ter][DuUnpd]":["pingkugnun"],"[Ter][PlUnpd]":["pingkunun"],"[Ter][SgUnpd]":["ping'umun"],"[Via]":["piaggun"],"[Via][DuUnpd]":["pingkunegnun"],"[Via][PlUnpd]":["pingkutgun"],"[Via][SgUnpd]":["ping'ukun"],"[Voc][DuUnpd]":["pingkuuk"],"[Voc][PlUnpd]":["pingkuut"],"[Voc][SgUnpd]":["pingyuuq","pingsuuq"]}}};

export const endingToEnglishTerms = {
"[Ind]":"Indicative (Statement Form)",
"[Intrg]":"Interrogative (Question Form)",
"[Opt]":"Optative (Command Form)",
"[Sbrd]":"Subordinative (Polite Command or -ing Form)",
"[Ptcp]":"Participial",
"[Prec]":"Precessive (before...)",
"[Cnsq]":"Consequential (because...)",
"[Cont]":"Contigent (whenever...)",
"[Conc]":"Concessive (although, even though, even if...)",
"[Cond]":"Conditional (if, when in the future...)",
"[CtmpI]":"Contemporative 1 (when in fthe past...)",
"[CtmpII]":"Contemporative 2 (while...)",
"[Abs]":"Absolutive",
"[Rel]":"Relative",
"[Abl_Mod]":"Ablative-Modalis (indirect object, from...)",
"[Loc]":"Localis (in, at...)",
"[Ter]":"Terminalis (to...)",
"[Sec_Ter]":"Second Terminalis (toward...)",
"[Via]":"Vialis (through, using...)",
"[Equ]":"Equalis (like, similar to...)",
"[Quant_Qual]":"Quantifier/Qualifier Inflection",
"[S_3Sg]":"he,\xa0she,\xa0it",
"[S_3Du]":"they\xa0(2)",
"[S_3Pl]":"they\xa0all\xa0(3+)",
"[S_1Sg]":"I",
"[S_1Du]":"we\xa0(2)",
"[S_1Pl]":"we\xa0all\xa0(3+)",
"[S_2Sg]":"you",
"[S_2Du]":"you\xa0(2)",
"[S_2Pl]":"you\xa0all\xa0(3+)",
"[S_4Sg]":"he, she, it (itself)",
"[S_4Du]":"they (2) (themselves)",
"[S_4Pl]":"they all (3+) (themselves)",
"[A_3Sg]":"he,\xa0she,\xa0it",
"[A_3Du]":"they\xa0(2)",
"[A_3Pl]":"they\xa0all\xa0(3+)",
"[A_1Sg]":"I",
"[A_1Du]":"we\xa0(2)",
"[A_1Pl]":"we\xa0all\xa0(3+)",
"[A_2Sg]":"you",
"[A_2Du]":"you\xa0(2)",
"[A_2Pl]":"you\xa0all\xa0(3+)",
"[A_4Sg]":"he, she, it (itself)",
"[A_4Du]":"they (2) (themselves)",
"[A_4Pl]":"they all (3+) (themselves)",
// "[P_3Sg]":"her,\xa0him,\xa0it\xa0(other)",
// "[P_3Du]":"the\xa0two\xa0of\xa0them\xa0(others)",
// "[P_3Pl]":"them\xa0all\xa0(3+)\xa0(others)",
"[P_3Sg]":"another",
"[P_3Du]":"two others",
"[P_3Pl]":"3+ others",
"[P_1Sg]":"me",
"[P_1Du]":"the\xa0two\xa0of\xa0us",
"[P_1Pl]":"us\xa0all\xa0(3+)",
"[P_2Sg]":"you",
"[P_2Du]":"the\xa0two\xa0of\xa0you",
"[P_2Pl]":"you\xa0all\xa0(3+)",
"[P_4Sg]":"her,\xa0him,\xa0it\xa0(itself)",
"[P_4Du]":"the\xa0two\xa0of\xa0them\xa0(themselves)",
"[P_4Pl]":"them\xa0all\xa0(3+)\xa0(themselves)",
"[SgUnpd]":"the one",
"[DuUnpd]":"the two",
"[PlUnpd]":"the 3+",
"[SgPosd]":"one",
"[DuPosd]":"two",
"[PlPosd]":"three or more",
"[3SgPoss]":"his/her/its\xa0(other)",
"[3DuPoss]":"their\xa0(2)\xa0(other)",
"[3PlPoss]":"their\xa0(3+)\xa0(other)",
"[1SgPoss]":"my",
"[1DuPoss]":"our\xa0(2)",
"[1PlPoss]":"our\xa0(3+)",
"[2SgPoss]":"your\xa0(1)",
"[2DuPoss]":"your\xa0(2)",
"[2PlPoss]":"your\xa0(3+)",
"[4SgPoss]":"his/her/its\xa0own",
"[4DuPoss]":"their\xa0own\xa0(2)",
"[4PlPoss]":"their\xa0own\xa0(3+)",
  "[3Sg]":"it\xa0(other)",
  "[3Du]":"them\xa0(2)\xa0(other)",
  "[3Pl]":"them\xa0(3+)\xa0(other)",
  "[1Sg]":"me",
  "[1Du]":"us\xa0(2)",
  "[1Pl]":"us\xa0(3+)",
  "[2Sg]":"you\xa0(1)",
  "[2Du]":"you\xa0(2)",
  "[2Pl]":"you\xa0(3+)",
  "[4Sg]":"itself",
  "[4Du]":"themselves\xa0(2)",
  "[4Pl]":"themselves\xa0(3+)",
};

export const endingEnglishDescriptions = {
"[Ind]":"(is, are, am)",
"[Intrg]":"(question)",
"[Opt]":"(do it!)",
"[Sbrd]":"(please do, being)",
"[Ptcp]":"(the one being, special case)",
"[Prec]":"(before)",
"[Cnsq]":"(because)",
"[Cont]":"(whenever)",
"[Conc]":"(although, even if)",
"[Cond]":"(if, when in future)",
"[CtmpI]":"(when in past)",
"[CtmpII]":"(while)",
"[Abs]":"the",
"[Rel]":"the",
"[Abl_Mod]":"[a, some, from]",
"[Loc]":"in or at",
"[Ter]":"to",
"[Sec_Ter]":"toward",
"[Via]":"through or using",
"[Equ]":"like or similar to",
"[Quant_Qual]":"Quantifier/Qualifier Inflection",
}

export const endingDescriptions = [
"1) statements; 2) “yes-no” questions, usually with enclitic =qaa",
"1) content questions; 2) exclamations with the postbase @5+pag- | ~vag-",
"1) commands, requests, suggestions; 2) statements in narrative with the postbase ki- and a third person ending",
"1) actions or states subordinate to that of the main verb and involving the same subject; 2) requests, commands, suggestions with a second person ending",
"1) exclamations, usually with tang; 2) certain special constructions (see maaten and =wa)",
"“before”",
"“because”",
"“whenever”",
"“although, even though, even if” ",
"“if, when (in the future)”",
"“when (in the past)” ",
"“while”",
"1) subject of an intransitive verb; 2) object of a transitive verb",
"1) subject of a transitive verb; 2) possessor; 3) “independent relative construction,” see section on roots in Generation Introduction, and Appendix 1, for further information",
"1) place from which, time from which; 2) indefinite object of an intransitive verb; 3) specifying information about a noun within a verb; 4) secondary object especially with verbs of speaking and giving; 5) instrument (only in some dialects)",
"1) place at which, time at which; 2) object of a comparison; 3) with postbase @+paa|~vaa and enclitic =lli in exclamations; 4) formal vocative",
"1) place to which, time to which; 2) subject of an embedded verb",
"1) route; 2) instrument; 3) part of a whole",
"1) comparison; 2) language specification; 3) price specification",
];

export const exampleSentences = [
"1) Pissurtuq. - It is hunting. 2) Maqillruuk-qaa? - Did they two took a steambath?",
"1) Qangvaq ayallrua? - When did he go? Caqatarcit? - What will you do? 2) Caperrnaqvagta. - How difficult it is.",
"1) Neri. - Eat. Taisgu. - Bring it here. 2) Tan'gaurluq qanqili, 'Maurluuq!, naw'un iterciqsia?' - The boy said (literally: let the boy say), 'Grandmother!, through where will I get in?'",
"1) Cukaluni aqvaqurtuq. - She is running quickly. 2) Qantan painqegcaarluku. - Lick your plate clean, please.",
"1) Tang, qavalria. - Look, it's sleeping. 2) Maaten itertua anelria. - I came in; lo and behold, he went out.",
"Ayagpailgan payugeskiu. - Before he leaves, bring him food.",
"Ayaksaituq arenqiapakaan ellalluk. - He hasn’t gone because of this bad weather.",
"Ner'aqami tamuanqegcaalartuq. - Whenever she eats, she chews her food well.",
"Pingraan ayagyugtua. - Even though that's the case, I want to go.",
"Anglirikuni elitnauristen͞guyugtuq. - When he grows up, he wants to be a teacher.",
"Akngirtuq atrallermini. - He got hurt when he was coming down.",
"Ayainanermini igtellruuq. - While he was going, he fell.",
"1) Saskaq kuv'uq. - The glass spilled. 2) Maqaruaq pissullrua. - He hunted the rabbit.",
"1) Angutem quyavikaa. - The man was thankful to her. 2) Ciquyam pania cen̄irtuq. - Ciquyaq's daughter is visiting.",
"1) Elitnaurvigmek utertuq. - She's coming home from the school. 2) Ner'uq akutamek. - She is eating some akutaq. 3) Nutaramek qayaliuq. - He is making a new kayak. 4) Aanama kuuvviaryuucimnek aptaanga. - My mother is asking me whether I want coffee.",
"1) Mermi uitauq. - It is in the water. 2) Aatamni sugtunruunga. - I am taller than my dad. 3) Akertem̄i-lli puqlanirpaa! - How warm the sun is! 4) Elpet angutmi, niicugninga. - You man, listen to me.",
"1) Kipusvigmun piyuaguq. - He's walking to the store. 2) Arnam neresqaa neqa taqukamun. - The woman asks/tells the bear to eat the fish.",
"1) Tumyarakun ayallruuq. - He went by the path. 2) Angyakun ayagtut. - They are going by boat. 3) Qercuallruunga it'gamkun. - I got frostbitten on my feet.",
"1) Aatamegcetun yurartut. - They are dancing like their father. 2) Una Yugtun cauga? - What is this in Yup'ik? 3) Akingqertuq malrugtun. - It is two dollars.",
];


export const accordionTitlesVerbs = [
  "Indicative (it is...)",
  "Interrogative (question)",
  "Optative (do it...)",
  "Subordinative (please do or it being...)",
  "Participial (exclamation or special case)",
  "Precessive (before...)",
  "Consequential (because...)",
  "Contigent (whenever...)",
  "Concessive (although, even though, even if...)",
  "Conditional (if, when in the future...)",
  "Contemporative 1 (when in the past...)",
  "Contemporative 2 (while...)",
  ];
// const accordionTitlesVerbs = [
//   "it is... (indicative)",
//   "question (interrogative)",
//   "do it... (optative)",
//   "please do or it being...(subordinative))",
//   "exclamation or special case (participial)",
//   "before... (precessive)",
//   "because... (consequential)",
//   "whenever... (contingent)",
//   "although, even though, even if... (concessive)",
//   "if, when in the future... (conditional)",
//   "when in the past... (contemporative 1)",
//   "while... (contemporative 2)",
//   ];
// const accordionTitlesVerbs = [
//   "it is... (Indicative)",
//   "question (Interrogative)",
//   "do it... (Optative)",
//   "please do or it being... (Subordinative))",
//   "exclamation or special case (Participial)",
//   "before... (Precessive)",
//   "because... (Consequential)",
//   "whenever... (Contingent)",
//   "although, even though, even if... (Concessive)",
//   "if, when in the future... (Conditional)",
//   "when in the past... (Contemporative 1)",
//   "while... (Contemporative 2)",
//   ];
export const accordionTitlesNouns = [
  "Absolutive (the)",
  "Relative (the)",
  "Ablative-Modalis (a, some, from)",
  "Localis (in, at)",
  "Terminalis (toward)",
  "Vialis (through, using)",
  "Equalis (like, similar to)",
  ];
export const accordionTitlesQuantQual = [
  "Absolutive (the)",
  "Relative (the possessor, owner)",
  "Ablative-Modalis (a, some, from)",
  "Localis (in, at)",
  "Terminalis (toward)",
  "Vialis (through, using)",
  "Equalis (like, similar to)",
  ];
export const persPronounLabels = ["[Abs]","[Rel]","[Abl_Mod]","[Loc]","[Ter]","[Via]","[Equ]"];

export const persPronounSubjects = [
"[3Sg]",
"[3Du]",
"[3Pl]",
"[1Sg]",
"[1Du]",
"[1Pl]",
"[2Sg]",
"[2Du]",
"[2Pl]",
"[4Sg]",
"[4Du]",
"[4Pl]",
];
export const persPronounsEnglish = [
"it\xa0(other)",
"them\xa0(2)\xa0(other)",
"them\xa0(3+)\xa0(other)",
"me",
"us\xa0(2)",
"us\xa0(3+)",
"you\xa0(1)",
"you\xa0(2)",
"you\xa0(3+)",
"itself",
"themselves\xa0(2)",
"themselves\xa0(3+)",
]
export const demPronounTitles = [
"over there or going away",
"across there",                                                
"up the slope",
"up above",
"inside, inland, or upriver",
"outside",
"down below or down the slope",
"downriver or near the exit",
"here, near speaker",
"there, near listener or in context",                                        
"coming this way",
]
export const demPronounSubjects = [
"[Abs][SgUnpd]",
"[Abs][DuUnpd]",
"[Abs][PlUnpd]",
"[Rel][SgUnpd]",
"[Rel][DuUnpd]",
"[Rel][PlUnpd]",
"[Abl_Mod][SgUnpd]",
"[Abl_Mod][DuUnpd]",
"[Abl_Mod][PlUnpd]",
"[Loc][SgUnpd]",
"[Loc][DuUnpd]",
"[Loc][PlUnpd]",
"[Ter][SgUnpd]",
"[Ter][DuUnpd]",
"[Ter][PlUnpd]",
"[Via][SgUnpd]",
"[Via][DuUnpd]",
"[Via][PlUnpd]",
"[Equ][SgUnpd]",
"[Equ][DuUnpd]",
"[Equ][PlUnpd]",
"[Voc][SgUnpd]",
"[Voc][DuUnpd]",
"[Voc][PlUnpd]",
"",
"[Loc]",
"[Ter]",
"[Sec_Ter]",
"[Abl]",
"[Via]",
"=i[Encl]",
]
export const demPronounEnglish = [
"absolutive singular",
"absolutive dual",
"absolutive plural",
"relative singular",
"relative dual",
"relative plural",
"abl-modalis singular",
"abl-modalis dual",
"abl-modalis plural",
"localis singular",
"localis dual",
"localis plural",
"terminalis singular",
"terminalis dual",
"terminalis plural",
"vialis singular",
"vialis dual",
"vialis plural",
"equalis singular",
"equalis dual",
"equalis plural",
"vocative singular",
"vocative dual",
"vocative plural",
"",
"localis",
"terminalis",
"second terminalis",
"ablative",
"vialis",
"predicative",
]

export const moods = ["[Ind]","[Intrg]","[Opt]","[Sbrd]","[Ptcp]","[Prec]","[Cnsq]","[Cont]","[Conc]","[Cond]","[CtmpI]","[CtmpII]","[Abs]","[Rel]","[Abl_Mod]","[Loc]", "[Ter]","[Via]","[Equ]","%5BQuant_Qual%5D","[PerPro]","[PerPro]","[PerPro]","[PerPro]","[PerPro]","[PerPro]","[PerPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]","[DemPro]",];
