export const speakerColors = {
  0:'red',
  1:'orange',
  2:'yellow',
  3:'green',
  4:'#2e2eb9',
  5:'purple',
  6:'purple',
  7:'black',
  8:'gold',
}

export const inupiaqSpeakerIDs = {
"Aglu (Whittier Williams Jr.)":0,
"I'yiiqpak (Gladys Pungowiyi)":1,
"Kapniaq (Lorena Williams)":2,
"Maqik (Mary Schaeffer)":3,
"Mumigaaluk (James Nageak)":4,
"Paniattaaq (Dr. Edna Ahgeak MacLean)":5,
"Taġġaq (Lawrence Kaplan)":6,
"Uyuġuluk (Marilyn Koezuna-Irelan)":7,
"Yaayuk (Bernadette Alvanna-Stimpfle)":8,    
}

export const nounoptions1 = [
  {id: 0, value: '00(3)', text:'the'},
  {id: 1, value: '11(3)', text:'my'},
  {id: 2, value: '21(3)', text:'your'},
  {id: 3, value: '31-1(3)', text:'his'},
  {id: 4, value: '31-2(3)', text:'her'},
  {id: 5, value: '31-3(3)', text:'its'},
  // {id: 6, value: '41(3)', text:'its own'},
  {id: 7, value: '12(3)', text:'our (two)'},
  {id: 8, value: '22(3)', text:'your (two)'},
  {id: 9, value: '32(3)', text:'their (two)'},
  // {id: 10, value: '42(3)', text:'their own (two)'},
  {id: 11, value: '13(3)', text:'our (3+)'},
  {id: 12, value: '23(3)', text:'your (3+)'},
  {id: 13, value: '33(3)', text:'their (3+)'},
  // {id: 14, value: '43(3)', text:'their own (3+)'},
];

export const nounoptionsmodalis = [
  {id: 0, value: '00(3)', text:'a, some'},
  {id: 1, value: '11(3)', text:'my'},
  {id: 2, value: '21(3)', text:'your'},
  {id: 3, value: '31-1(3)', text:'his'},
  {id: 4, value: '31-2(3)', text:'her'},
  {id: 5, value: '31-3(3)', text:'its'},
  // {id: 6, value: '41(3)', text:'its own'},
  {id: 7, value: '12(3)', text:'our (two)'},
  {id: 8, value: '22(3)', text:'your (two)'},
  {id: 9, value: '32(3)', text:'their (two)'},
  // {id: 10, value: '42(3)', text:'their own (two)'},
  {id: 11, value: '13(3)', text:'our (3+)'},
  {id: 12, value: '23(3)', text:'your (3+)'},
  {id: 13, value: '33(3)', text:'their (3+)'},
];

export const nounoptions2 = [
  {id: 0, value: '1', text:'one'},
  {id: 1, value: '2', text:'two'},
  {id: 2, value: '3', text:'three or more'},
];

export const options1 = [
  {id: 0, value: 's11(1)', text:'I', otext:'me'},
  {id: 1, value: 's21(1)', text:'you', otext:'you'},
  {id: 2, value: 's31-1(1)', text:'he', otext:'him'},
  {id: 3, value: 's31-2(1)', text:'she', otext:'her'},
  {id: 4, value: 's31-3(1)', text:'it', otext:'it'},
  // {id: 5, value: 's41(1)', text:'its own', otext:'its own'},
  {id: 6, value: 's12(1)', text:'the two of us', otext:'the two of us'},
  {id: 7, value: 's22(1)', text:'the two of you', otext:'the two of you'},
  {id: 8, value: 's32(1)', text:'the two of them', otext:'the two of them'},
  // {id: 9, value: 's42(1)', text:'their own (two)', otext:'their own (two)'},
  {id: 10, value: 's13(1)', text:'we all (3+)', otext:'us all (3+)'},
  {id: 11, value: 's23(1)', text:'you all (3+)', otext:'you all (3+)'},
  {id: 12, value: 's33(1)', text:'they all (3+)', otext:'them all (3+)'},
  // {id: 13, value: 's43(1)', text:'their own (3+)', otext:'their own (3+)'}
];

export const options2 = [
  {id: 0, value: 'o11(2)', text:'me', ptext:'my'},
  {id: 1, value: 'o21(2)', text:'you', ptext:'your'},
  {id: 2, value: 'o31-1(2)', text:'him', ptext:'his'},
  {id: 3, value: 'o31-2(2)', text:'her', ptext:'her'},
  {id: 4, value: 'o31-3(2)', text:'it', ptext:'its'},
  // {id: 5, value: 'o41(2)', text:'its own', ptext:'its own'},
  {id: 6, value: 'o12(2)', text:'the two of us', ptext:'our (two)'},
  {id: 7, value: 'o22(2)', text:'the two of you', ptext:'your (two)'},
  {id: 8, value: 'o32(2)', text:'the two of them', ptext:'their (two)'},
  // {id: 9, value: 'o42(2)', text:'their own (two)', ptext:'their own (two)'},
  {id: 10, value: 'o13(2)', text:'us all (3+)', ptext:'our (3+)'},
  {id: 11, value: 'o23(2)', text:'you all (3+)', ptext:'your (3+)'},
  {id: 12, value: 'o33(2)', text:'them all (3+)', ptext:'their (3+)'},
  // {id: 13, value: 'o43(2)', text:'their own (3+)', ptext:'their own (3+)'},
];


export const options3 = [
  {id: 0, value: 'o11(3)', text:'my'},
  {id: 1, value: 'o21(3)', text:'your'},
  {id: 2, value: 'o31-1(3)', text:'his'},
  {id: 3, value: 'o31-2(3)', text:'her'},
  {id: 4, value: 'o31-3(3)', text:'its'},
  // {id: 5, value: 'o41(2)', text:'its own'},
  {id: 6, value: 'o12(3)', text:'our (two)'},
  {id: 7, value: 'o22(3)', text:'your (two)'},
  {id: 8, value: 'o32(3)', text:'their (two)'},
  // {id: 9, value: 'o42(2)', text:'their own (two)'},
  {id: 10, value: 'o13(3)', text:'our (3+)'},
  {id: 11, value: 'o23(3)', text:'your (3+)'},
  {id: 12, value: 'o33(3)', text:'their (3+)'},
  // {id: 13, value: 'o43(2)', text:'their own (3+)', ptext:'their own (3+)'},
];

export const retrieveSubjectObject =
  {'11(1)':'I',
  '21(1)':'you',
  '31-1(1)':'he',
  '31-2(1)':'she',
  '31-3(1)':'it',
  '41(1)':'its own',
  '12(1)':'the two of us',
  '22(1)':'the two of you',
  '32(1)':'the two of them',
  '42(1)':'their own (two)',
  '13(1)':'we all (3+)',
  '23(1)':'you all (3+)',
  '33(1)':'they all (3+)',
  '43(1)':'their own (3+)',
  '11(2)':'me',
  '21(2)':'you',
  '31-1(2)':'him',
  '31-2(2)':'her',
  '31-3(2)':'it',
  '41(2)':'its own',
  '12(2)':'the two of us',
  '22(2)':'the two of you',
  '32(2)':'the two of them',
  '42(2)':'their own (two)',
  '13(2)':'us all (3+)',
  '23(2)':'you all (3+)',
  '33(2)':'them all (3+)',
  '43(2)':'their own (3+)',
  '11(3)':'my',
  '21(3)':'your',
  '31-1(3)':'his',
  '31-2(3)':'her',
  '31-3(3)':'its',
  '41(3)':'its own',
  '12(3)':'our (two)',
  '22(3)':'your (two)',
  '32(3)':'their (two)',
  '42(3)':'their own (two)',
  '13(3)':'our (3+)',
  '23(3)':'your (3+)',
  '33(3)':'their (3+)',
  '43(3)':'their own (3+)'}
;

export const retrieveReflexiveSubjectPronoun =
{
  'self':
  {
  's11(1)':'myself',
  's21(1)':'yourself',
  's31-1(1)':'himself',
  's31-2(1)':'herself',
  's31-3(1)':'itself',
  // '41(1)':'its own',
  's12(1)':'ourselves',
  's22(1)':'yourselves',
  's32(1)':'themselves',
  // '42(1)':'their own (two)',
  's13(1)':'ourselves',
  's23(1)':'yourselves',
  's33(1)':'themselves',
  },
  'poss':
  {
  's11(1)':'my',
  's21(1)':'your',
  's31-1(1)':'his',
  's31-2(1)':'her',
  's31-3(1)':'its',
  // '41(1)':'its own',
  's12(1)':'our',
  's22(1)':'your',
  's32(1)':'their',
  // '42(1)':'their own (two)',
  's13(1)':'our',
  's23(1)':'your',
  's33(1)':'their',
  },
  'regSub':
  {
  's11(1)':'I',
  's21(1)':'you',
  's31-1(1)':'he',
  's31-2(1)':'she',
  's31-3(1)':'it',
  // '41(1)':'its own',
  's12(1)':'we',
  's22(1)':'you two',
  's32(1)':'they',
  // '42(1)':'their own (two)',
  's13(1)':'we all',
  's23(1)':'you all',
  's33(1)':'they all',
  },
  'regObj':
  {
  's11(1)':'me',
  's21(1)':'you',
  's31-1(1)':'him',
  's31-2(1)':'her',
  's31-3(1)':'it',
  // '41(1)':'its own',
  's12(1)':'the two of us',
  's22(1)':'the two of you',
  's32(1)':'the two of them',
  // '42(1)':'their own (two)',
  's13(1)':'us all',
  's23(1)':'you all',
  's33(1)':'them all',
  },
};



// export const retrieveReflexiveSubjectPronounSelf =
//   {
//   's11(1)':'myself',
//   's21(1)':'yourself',
//   's31-1(1)':'himself',
//   's31-2(1)':'herself',
//   's31-3(1)':'itself',
//   // '41(1)':'its own',
//   's12(1)':'ourselves',
//   's22(1)':'yourselves',
//   's32(1)':'themselves',
//   // '42(1)':'their own (two)',
//   's13(1)':'ourselves',
//   's23(1)':'yourselves',
//   's33(1)':'themselves',
//   // '43(1)':'their own (3+)'
// }
// ;

export const VVpostbases = {
    "1": {
        "exp": "\u2013nge[V\u2192V]",
        "exp_display": "\u2013nge",
        "subj": "he",
        "is": true,
        "description": "beginning to",
        "gen_preverb": "beginning to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "begin to",
        "inf_preverb_after": "i",
        "ger_preverb": "beginning to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "2": {
        "exp": "@~+ngiate[V\u2192V]",
        "exp_display": "@\u00b2~+ngiate\u00b0",
        "subj": "he",
        "is": true,
        "description": "inept at",
        "gen_preverb": "inept at",
        "gen_preverb_after": "g",
        "past_preverb": "",
        "past_preverb_after": "g",
        "inf_preverb": "be inept at",
        "inf_preverb_after": "g",
        "ger_preverb": "being inept at",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "3": {
        "exp": "@~+ngig[V\u2192V]",
        "exp_display": "@\u00b2~+ngig",
        "subj": "he",
        "is": true,
        "description": "adept at",
        "gen_preverb": "adept at",
        "gen_preverb_after": "g",
        "past_preverb": "",
        "past_preverb_after": "g",
        "inf_preverb": "be adept at",
        "inf_preverb_after": "g",
        "ger_preverb": "being adept at",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "4": {
        "exp": "@~+nginar[V\u2192V]",
        "exp_display": "@\u00b2~+nginar",
        "subj": "he",
        "is": true,
        "description": "merely (with no attendant complications)",
        "gen_preverb": "merely (with no attendant complications)",
        "past_preverb": "merely (with no attendant complications)",
        "inf_preverb": "merely (with no attendant complications)",
        "ger_preverb": "merely (with no attendant complications)",
        "match_case": true
    },
    "5": {
        "exp": "\u2013ngnagar[V\u2192V]",
        "exp_display": "\u2013ngnagar",
        "description": "in an irritating way",
        "postverb": "in an irritating way",
        "match_case": true
    },
    "6": {
        "exp": "\u2013ngnaqe[V\u2192V]",
        "exp_display": "\u2013ngnaqe",
        "subj": "he",
        "is": true,
        "description": "trying to",
        "gen_preverb": "trying to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "try to",
        "inf_preverb_after": "i",
        "ger_preverb": "trying to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "7": {
        "exp": "\u2013ngnaqsaaqe[V\u2192V]",
        "exp_display": "\u2013ngnaqsaaqe",
        "subj": "he",
        "is": true,
        "description": "trying unsuccessfully to",
        "gen_preverb": "trying unsuccessfully to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "try unsuccessfully to",
        "inf_preverb_after": "i",
        "ger_preverb": "trying unsuccessfully to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "8": {
        "exp": "\u2013ngnatug[V\u2192V]",
        "exp_display": "\u2013ngnatug",
        "subj": "he",
        "is": true,
        "description": "trying hard to",
        "gen_preverb": "trying hard to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "try hard to",
        "inf_preverb_after": "i",
        "ger_preverb": "trying hard to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "9": {
        "exp": "@\u2013ngqa[V\u2192V]",
        "exp_display": "@\u2075\u2013ngqa",
        "subj": "he",
        "is": true,
        "description": "in a state of",
        "gen_preverb": "in a state of",
        "gen_preverb_after": "g",
        "past_preverb": "",
        "past_preverb_after": "g",
        "inf_preverb": "be in a state of",
        "inf_preverb_after": "g",
        "ger_preverb": "being in a state of",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "10": {
        "exp": "\u2013ngssaar(ar)[V\u2192V]",
        "exp_display": "\u2013ngssaar(ar)",
        "description": "secretively, unnoticeably",
        "postverb": "secretively, unnoticeably",
        "match_case": true
    },
    "11": {
        "exp": "\u2013ngssag[V\u2192V]",
        "exp_display": "\u2013ngssag",
        "description": "to no particular end",
        "postverb": "to no particular end",
        "match_case": true
    },
    "12": {
        "exp": "\u2013ngssi[V\u2192V]",
        "exp_display": "\u2013ngssi",
        "description": "to no particular end",
        "postverb": "to no particular end",
        "match_case": true
    },
    "13": {
        "exp": "@~\u2013nguar[V\u2192V]",
        "exp_display": "@\u00b2~\u2013nguar",
        "subj": "he",
        "is": true,
        "description": "pretending to",
        "gen_preverb": "pretending to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "pretend to",
        "inf_preverb_after": "i",
        "ger_preverb": "pretending to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "16": {
        "exp": "@~+niar[V\u2192V]",
        "exp_display": "@\u00b9~+niar",
        "description": "in the future",
        "postverb": "in the future",
        "match_case": true
    },
    "17": {
        "exp": "@~+niarar[V\u2192V]",
        "exp_display": "@\u00b9~+niarar",
        "subj": "he",
        "is": true,
        "description": "soon going to",
        "gen_preverb": "soon going to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "soon be going",
        "inf_preverb_after": "g",
        "ger_preverb": "soon being going",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "24": {
        "exp": "\u2013nqegcaar(ar)[V\u2192V]",
        "exp_display": "\u2013nqegcaar(ar)",
        "description": "completely, thoroughly",
        "postverb": "completely, thoroughly",
        "match_case": true
    },
    "25": {
        "exp": "\u2013nqigte[V\u2192V]",
        "exp_display": "\u2013nqigte",
        "description": "again",
        "postverb": "again",
        "match_case": true
    },
    "26": {
        "exp": "\u2013nricen\u0304ar[V\u2192V]",
        "exp_display": "\u2013nricen\u0304ar",
        "subj": "he",
        "is": true,
        "description": "not (having changed his mind)",
        "gen_preverb": "not (having changed his mind)",
        "past_preverb": "not (having changed his mind)",
        "inf_preverb": "not (having changed his mind)",
        "ger_preverb": "not (having changed his mind)",
        "match_case": true
    },
    "27": {
        "exp": "\u2013nrilkurte[V\u2192V]",
        "exp_display": "\u2013nrilkurte",
        "subj": "he",
        "is": true,
        "description": "keeping ^himself^ from",
        "gen_preverb": "keeping ^himself^ from",
        "gen_preverb_after": "g",
        "past_preverb": "",
        "past_preverb_after": "g",
        "inf_preverb": "keep ^himself^ from",
        "inf_preverb_after": "g",
        "ger_preverb": "keeping ^himself^ from",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "28": {
        "exp": "\u2013nrir[V\u2192V]",
        "exp_display": "\u2013nrir",
        "subj": "he",
        "is": true,
        "description": "no longer",
        "gen_preverb": "no longer",
        "past_preverb": "no longer",
        "inf_preverb": "no longer",
        "ger_preverb": "no longer",
        "match_case": true
    },
    "29": {
        "exp": "\u2013nritar(ar)[V\u2192V]",
        "exp_display": "\u2013nritar(ar)",
        "subj": "he",
        "is": true,
        "description": "almost",
        "gen_preverb": "almost",
        "past_preverb": "almost",
        "inf_preverb": "almost",
        "ger_preverb": "almost",
        "match_case": true
    },
    "30": {
        "exp": "\u2013nrite[V\u2192V]",
        "exp_display": "\u2013nrite\u00b0",
        "subj": "he",
        "is": true,
        "description": "not",
        "gen_preverb": "not",
        "past_preverb": "not",
        "inf_preverb": "not",
        "ger_preverb": "not",
        "match_case": true
    },
    "31": {
        "exp": "\u2013nru[V\u2192V]",
        "exp_display": "\u2013nru",
        "description": "moreso",
        "postverb": "moreso",
        "match_case": true
    },
    "32": {
        "exp": "@+paalug|~vaalug[V\u2192V]",
        "exp_display": "@\u2075+p|~vaalug",
        "description": "for the first time",
        "postverb": "for the first time",
        "match_case": true
    },
    "33": {
        "exp": "@+pailug|~vailug[V\u2192V]",
        "exp_display": "@\u2075+p|~vailug",
        "description": "for the first time",
        "postverb": "for the first time",
        "match_case": true
    },
    "34": {
        "exp": "\u2013pacug[V\u2192V]",
        "exp_display": "\u2013pacug",
        "description": "poorly, dearly",
        "postverb": "poorly, dearly",
        "match_case": true
    },
    "35": {
        "exp": "@+pag|~vag1[V\u2192V]",
        "exp_display": "@\u2075+p|~vag",
        "description": "so well",
        "postverb": "so well",
        "match_case": true
    },
    "36": {
        "exp": "@+pakar|~vakar[V\u2192V]",
        "exp_display": "@\u2075+p|~vakar",
        "description": "so much",
        "postverb": "so much",
        "match_case": true
    },
    "37": {
        "exp": "\u2013qpakar[V\u2192V]",
        "exp_display": "\u2013qpakar",
        "description": "so much",
        "postverb": "so much",
        "match_case": true
    },
    "38": {
        "exp": "@+pallag|~vallag[V\u2192V]",
        "exp_display": "@\u2075+p|~vallag",
        "description": "intensely",
        "postverb": "intensely",
        "match_case": true
    },
    "39": {
        "exp": "@+pallug|~vallug[V\u2192V]",
        "exp_display": "@\u2075+p|~vallug",
        "description": "the most",
        "postverb": "the most",
        "match_case": true
    },
    "40": {
        "exp": "@+pallur|~vallur[V\u2192V]",
        "exp_display": "@\u2075+p|~vallur",
        "description": "the most",
        "postverb": "the most",
        "match_case": true
    },
    "41": {
        "exp": "+peke|.vke[V\u2192V]",
        "exp_display": "+p|.vke\u00b0",
        "subj": "he",
        "is": true,
        "description": "not",
        "gen_preverb": "not",
        "past_preverb": "not",
        "inf_preverb": "not",
        "ger_preverb": "not",
        "match_case": true
    },
    "42": {
        "exp": "+pege|.vke[V\u2192V]",
        "exp_display": "+p|.vge\u00b0",
        "subj": "he",
        "is": true,
        "description": "not",
        "gen_preverb": "not",
        "past_preverb": "not",
        "inf_preverb": "not",
        "ger_preverb": "not",
        "match_case": true
    },
    "43": {
        "exp": "+pigainar[V\u2192V]",
        "exp_display": "+pigainar",
        "subj": "he",
        "is": true,
        "description": "actually (surprisingly)",
        "gen_preverb": "actually (surprisingly)",
        "past_preverb": "actually (surprisingly)",
        "inf_preverb": "actually (surprisingly)",
        "ger_preverb": "actually (surprisingly)",
        "match_case": true
    },
    "44": {
        "exp": "\u2013pigainar[V\u2192V]",
        "exp_display": "\u2013pigainar",
        "subj": "he",
        "is": true,
        "description": "actually (surprisingly)",
        "gen_preverb": "actually (surprisingly)",
        "past_preverb": "actually (surprisingly)",
        "inf_preverb": "actually (surprisingly)",
        "ger_preverb": "actually (surprisingly)",
        "match_case": true
    },
    "45": {
        "exp": "\u2013pig[V\u2192V]",
        "exp_display": "\u2013pig",
        "subj": "he",
        "is": true,
        "description": "really",
        "gen_preverb": "really",
        "past_preverb": "really",
        "inf_preverb": "really",
        "ger_preverb": "really",
        "match_case": true
    },
    "46": {
        "exp": "\u2013piar[V\u2192V]",
        "exp_display": "\u2013piar",
        "subj": "he",
        "is": true,
        "description": "really",
        "gen_preverb": "really",
        "past_preverb": "really",
        "inf_preverb": "really",
        "ger_preverb": "really",
        "match_case": true
    },
    "47": {
        "exp": "\u2013pigar[V\u2192V]",
        "exp_display": "\u2013pigar",
        "description": "very much so",
        "postverb": "very much so",
        "match_case": true
    },
    "48": {
        "exp": "\u2013qaci[V\u2192V]",
        "exp_display": "\u2013q\u0332aci",
        "description": "in a minor way",
        "postverb": "in a minor way",
        "match_case": true
    },
    "49": {
        "exp": "\u2013qainar[V\u2192V]",
        "exp_display": "\u2013q\u0332ainar",
        "subj": "he",
        "is": true,
        "description": "merely",
        "gen_preverb": "merely",
        "past_preverb": "merely",
        "inf_preverb": "merely",
        "ger_preverb": "merely",
        "match_case": true
    },
    "50": {
        "exp": "\u2013qainaurte[V\u2192V]",
        "exp_display": "\u2013q\u0332ainaurte",
        "subj": "he",
        "is": true,
        "description": "ready to",
        "gen_preverb": "ready to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be ready to",
        "inf_preverb_after": "i",
        "ger_preverb": "being ready to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "51": {
        "exp": "\u2013qapiar(ar)[V\u2192V]",
        "exp_display": "\u2013q\u0332apiar(ar)",
        "description": "very much so",
        "postverb": "very much so",
        "match_case": true
    },
    "52": {
        "exp": "\u2013qapigte[V\u2192V]",
        "exp_display": "\u2013q\u0332apigte",
        "description": "very much so",
        "postverb": "very much so",
        "match_case": true
    },
    "53": {
        "exp": "\u2013qaqe1[V\u2192V]",
        "exp_display": "\u2013q\u0332araqe",
        "description": "intermittently",
        "postverb": "intermittently",
        "match_case": true
    },
    "54": {
        "exp": "@qaqe2[V\u2192V]",
        "exp_display": "@\u2075qaqe",
        "description": "one after another",
        "postverb": "one after another",
        "match_case": true
    },
    "55": {
        "exp": "\u2013qaqu[V\u2192V]",
        "exp_display": "\u2013q\u0332aqu",
        "description": "now and then",
        "postverb": "now and then",
        "match_case": true
    },
    "56": {
        "exp": "\u2013qaqur(ar)[V\u2192V]",
        "exp_display": "\u2013q\u0332aqur(ar)",
        "description": "now and then",
        "postverb": "now and then",
        "match_case": true
    },
    "57": {
        "exp": "\u2013qar[V\u2192V]",
        "exp_display": "\u2013q\u0332ar",
        "description": "briefly",
        "postverb": "briefly",
        "match_case": true
    },
    "59": {
        "exp": "\u2013qataar(ar)[V\u2192V]",
        "exp_display": "\u2013q\u0332ataar(ar)",
        "subj": "he",
        "is": true,
        "description": "slowly starting to",
        "gen_preverb": "slowly starting to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "slowly start to",
        "inf_preverb_after": "i",
        "ger_preverb": "slowly starting to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "60": {
        "exp": "\u2013qatar[V\u2192V]",
        "exp_display": "\u2013q\u0332atar",
        "subj": "he",
        "is": true,
        "description": "about to",
        "gen_preverb": "about to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be about to",
        "inf_preverb_after": "i",
        "ger_preverb": "being about to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "61": {
        "exp": "\u2013qcaar(ar)[V\u2192V]",
        "exp_display": "\u2013q\u0332caar(ar)",
        "subj": "he",
        "is": true,
        "description": "trying (despite difficulties) to",
        "gen_preverb": "trying (despite difficulties) to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "try (despite difficulties) to",
        "inf_preverb_after": "i",
        "ger_preverb": "trying (despite difficulties) to ",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "62": {
        "exp": "\u2013qerte[V\u2192V]",
        "exp_display": "\u2013qerte",
        "description": "suddenly, hurriedly",
        "postverb": "suddenly, hurriedly",
        "match_case": true
    },
    "63": {
        "exp": "\u2013qetaar[V\u2192V]",
        "exp_display": "\u2013q\u0332etaar",
        "description": "repeatedly at intervals",
        "postverb": "repeatedly at intervals",
        "match_case": true
    },
    "64": {
        "exp": "@\u2013qtaar[V\u2192V]",
        "exp_display": "@\u2013qtaar",
        "description": "repeatedly at intervals",
        "postverb": "repeatedly at intervals",
        "match_case": true
    },
    "65": {
        "exp": "\u2013qtar[V\u2192V]",
        "exp_display": "\u2013q\u0332tar",
        "description": "weakly, helplessly, dearly",
        "postverb": "weakly, helplessly, dearly",
        "match_case": true
    },
    "66": {
        "exp": "\u2013qtarar(ar)[V\u2192V]",
        "exp_display": "\u2013q\u0332tarar(ar)",
        "description": "slowly and with difficulty because of disability",
        "postverb": "slowly and with difficulty because of disability",
        "match_case": true
    },
    "67": {
        "exp": "\u2013qu1[V\u2192V]",
        "exp_display": "\u2013q\u0332u",
        "description": "one after another",
        "postverb": "one after another",
        "match_case": true
    },
    "68": {
        "exp": "@\u2013qur[V\u2192V]",
        "exp_display": "@\u2075\u2013qur",
        "description": "using repeated action to accomplish the act",
        "postverb": "using repeated action to accomplish the act",
        "match_case": true
    },
    "69": {
        "exp": "\u2013rpaga[V\u2192V]",
        "exp_display": "\u2013r\u0332paga",
        "description": "hard at intervals",
        "postverb": "hard at intervals",
        "match_case": true
    },
    "70": {
        "exp": "\u2013rpag[V\u2192V]",
        "exp_display": "\u2013r\u0332pag",
        "description": "hard",
        "postverb": "hard",
        "match_case": true
    },
    "71": {
        "exp": "\u2013rpakar[V\u2192V]",
        "exp_display": "\u2013r\u0332pakar",
        "description": "so much, for so long",
        "postverb": "so much, for so long",
        "match_case": true
    },
    "72": {
        "exp": "@\u2013rqe1[V\u2192V]",
        "exp_display": "@\u2075\u2013rqe",
        "description": "one after another",
        "postverb": "one after another",
        "match_case": true
    },
    "75": {
        "exp": "\u2013rrar[V\u2192V]",
        "exp_display": "\u2013r\u0332r\u0332ar",
        "description": "just barely",
        "postverb": "just barely",
        "match_case": true
    },
    "76": {
        "exp": "\u2013rraar[V\u2192V]",
        "exp_display": "\u2013r\u0332r\u0332aar",
        "description": "first",
        "postverb": "first",
        "match_case": true
    },
    "77": {
        "exp": "\u2013rrlainar[V\u2192V]",
        "exp_display": "\u2013r\u0332r\u0332lainar",
        "subj": "he",
        "is": true,
        "description": "constantly",
        "gen_preverb": "constantly",
        "past_preverb": "constantly",
        "inf_preverb": "constantly",
        "ger_preverb": "constantly",
        "match_case": true
    },
    "78": {
        "exp": "\u2013rrluar(ar)[V\u2192V]",
        "exp_display": "\u2013r\u0332r\u0332luar(ar)",
        "description": "a little bit",
        "postverb": "a little bit",
        "match_case": true
    },
    "79": {
        "exp": "\u2013rrlug[V\u2192V]",
        "exp_display": "\u2013r\u0332r\u0332lug",
        "subj": "he",
        "is": true,
        "description": "somewhat",
        "gen_preverb": "somewhat",
        "past_preverb": "somewhat",
        "inf_preverb": "somewhat",
        "ger_preverb": "somewhat",
        "match_case": true
    },
    "80": {
        "exp": "\u2013rrlugte[V\u2192V]",
        "exp_display": "\u2013r\u0332r\u0332lugte",
        "subj": "he",
        "is": true,
        "description": "somewhat",
        "gen_preverb": "somewhat",
        "past_preverb": "somewhat",
        "inf_preverb": "somewhat",
        "ger_preverb": "somewhat",
        "match_case": true
    },
    "81": {
        "exp": "\u2013q(ur)lur[V\u2192V]",
        "exp_display": "\u2013r\u0332(ur)lur",
        "description": "poorly, dearly",
        "postverb": "poorly, dearly",
        "match_case": true
    },
    "82": {
        "exp": "\u2013rvaar[V\u2192V]",
        "exp_display": "\u2013r\u0332vaar",
        "description": "very much so",
        "postverb": "very much so",
        "match_case": true
    },
    "83": {
        "exp": "\u2013rvag[V\u2192V]",
        "exp_display": "\u2013r\u0332vag",
        "description": "very much so",
        "postverb": "very much so",
        "match_case": true
    },
    "84": {
        "exp": "\u2013sciigate[V\u2192V]",
        "exp_display": "\u2013sciigate\u00b0",
        "subj": "he",
        "is": true,
        "description": "unable to",
        "gen_preverb": "unable to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be unable to",
        "inf_preverb_after": "i",
        "ger_preverb": "being unable to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "89": {
        "exp": "\u2013ssaag1[V\u2192V]",
        "exp_display": "\u2013ssaag",
        "subj": "he",
        "is": true,
        "description": "trying to",
        "gen_preverb": "trying to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "try to",
        "inf_preverb_after": "i",
        "ger_preverb": "trying to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "90": {
        "exp": "\u2013ssaag3[V\u2192V]",
        "exp_display": "\u2013ssaag",
        "description": "too much",
        "postverb": "too much",
        "match_case": true
    },
    "91": {
        "exp": "\u2013ssiyaag[V\u2192V]",
        "exp_display": "\u2013ssiyaag",
        "description": "too much",
        "postverb": "too much",
        "match_case": true
    },
    "93": {
        "exp": "@+ta2[V\u2192V]",
        "exp_display": "@\u00b2+ta",
        "description": "to a certain degree",
        "postverb": "to a certain degree",
        "match_case": true
    },
    "94": {
        "exp": "+taagute[V\u2192V]",
        "exp_display": "+taagute",
        "description": "back and forth",
        "postverb": "back and forth",
        "match_case": true
    },
    "95": {
        "exp": "@+taar1[V\u2192V]",
        "exp_display": "@\u2074+taar",
        "subj": "he",
        "is": true,
        "description": "acting so as to try to make others feel that ^he^ is",
        "gen_preverb": "acting so as to try to make others feel that ^he^ is",
        "gen_preverb_after": "g",
        "past_preverb": "",
        "past_preverb_after": "g",
        "inf_preverb": "act so as to try to make others feel that ^he^ is",
        "inf_preverb_after": "g",
        "ger_preverb": "acting so as to try to make others feel that ^he^ is",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "96": {
        "exp": "+tar1[V\u2192V]",
        "exp_display": "+tar",
        "subj": "he",
        "is": false,
        "description": "tends to often",
        "gen_preverb": "tends to often",
        "gen_preverb_after": "i",
        "past_preverb": "tended to often",
        "past_preverb_after": "i",
        "inf_preverb": "tend to often",
        "inf_preverb_after": "i",
        "ger_preverb": "tending to often",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "103": {
        "exp": "+ter[V\u2192V]",
        "exp_display": "+ter",
        "description": "suddenly and willfully",
        "postverb": "suddenly and willfully",
        "match_case": true
    },
    "104": {
        "exp": "\u2013tngurte[V\u2192V]",
        "exp_display": "\u2013tngurte",
        "description": "unexpectedly",
        "postverb": "unexpectedly",
        "match_case": true
    },
    "105": {
        "exp": "\u2013tmurte2[V\u2192V]",
        "exp_display": "\u2013tmurte",
        "description": "unexpectedly",
        "postverb": "unexpectedly",
        "match_case": true
    },
    "106": {
        "exp": "\u2013tu[V\u2192V]",
        "exp_display": "\u2013tu",
        "description": "customarily",
        "postverb": "customarily",
        "match_case": true
    },
    "107": {
        "exp": "+tuinar[V\u2192V]",
        "exp_display": "+tuinar",
        "subj": "it",
        "is": true,
        "description": "always",
        "gen_preverb": "always",
        "past_preverb": "always",
        "inf_preverb": "always",
        "ger_preverb": "always",
        "match_case": true
    },
    "109": {
        "exp": "\u2013turnir[V\u2192V]",
        "exp_display": "\u2013turnir",
        "subj": "it",
        "is": true,
        "description": "proficiently able to",
        "gen_preverb": "proficiently able to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be proficiently able to",
        "inf_preverb_after": "i",
        "ger_preverb": "being proficiently able to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "110": {
        "exp": "@~+(ng)uar[V\u2192V]",
        "exp_display": "@\u00b2~+(ng)uar",
        "subj": "it",
        "is": true,
        "description": "pretending to",
        "gen_preverb": "pretending to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "pretend to",
        "inf_preverb_after": "i",
        "ger_preverb": "pretending to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "111": {
        "exp": "@+`(g|t)ur(ar)[V\u2192V]",
        "exp_display": "@\u02c1+`(g|t)ur(ar)",
        "subj": "it",
        "is": true,
        "description": "continuing to",
        "gen_preverb": "continuing to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "continue to",
        "inf_preverb_after": "i",
        "ger_preverb": "continuing to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "112": {
        "exp": "@+`(g|t)urainar[V\u2192V]",
        "exp_display": "@\u02c1+`(g|t)urainar",
        "subj": "it",
        "is": true,
        "description": "finally (after desiring to but not being able to)",
        "gen_preverb": "finally (after desiring to but not being able to)",
        "past_preverb": "finally (after desiring to but not being able to)",
        "inf_preverb": "finally (after desiring to but not being able to)",
        "ger_preverb": "finally (after desiring to but not being able to)",
        "match_case": true
    },
    "113": {
        "exp": "@+`(g|t)uralar[V\u2192V]",
        "exp_display": "@\u02c1+`(g|t)uralar",
        "subj": "it",
        "is": true,
        "description": "always",
        "gen_preverb": "always",
        "past_preverb": "always",
        "inf_preverb": "always",
        "ger_preverb": "always",
        "match_case": true
    },
    "114": {
        "exp": "@+`(g|t)ur(ar)lar[V\u2192V]",
        "exp_display": "@\u02c1+`(g|t)ur(ar)lar",
        "subj": "it",
        "is": true,
        "description": "always",
        "gen_preverb": "always",
        "past_preverb": "always",
        "inf_preverb": "always",
        "ger_preverb": "always",
        "match_case": true
    },
    "115": {
        "exp": "@+`(g|t)uratu[V\u2192V]",
        "exp_display": "@\u02c1+`(g|t)uratu",
        "subj": "it",
        "is": true,
        "description": "always",
        "gen_preverb": "always",
        "past_preverb": "always",
        "inf_preverb": "always",
        "ger_preverb": "always",
        "match_case": true
    },
    "116": {
        "exp": "\u2013vguar(ar)[V\u2192V]",
        "exp_display": "\u2013vguar(ar)",
        "description": "a little bit",
        "postverb": "a little bit",
        "match_case": true
    },
    "117": {
        "exp": "\u2013vialug[V\u2192V]",
        "exp_display": "\u2013vialug",
        "description": "clumsily",
        "postverb": "clumsily",
        "match_case": true
    },
    "118": {
        "exp": "\u2013viite[V\u2192V]",
        "exp_display": "\u2013viite",
        "subj": "it",
        "is": false,
        "description": "leaves no room or place to",
        "gen_preverb": "leaves no room or place to",
        "gen_preverb_after": "i",
        "past_preverb": "left no room or place to",
        "past_preverb_after": "i",
        "inf_preverb": "leave no room or place to",
        "inf_preverb_after": "i",
        "ger_preverb": "leaving no room or place to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "120": {
        "exp": "\u2013vlaag[V\u2192V]",
        "exp_display": "\u2013vlaag",
        "description": "insufficiently",
        "postverb": "insufficiently",
        "match_case": true
    },
    "121": {
        "exp": "\u2013vlugte[V\u2192V]",
        "exp_display": "\u2013vlugte",
        "description": "sloppily",
        "postverb": "sloppily",
        "match_case": true
    },
    "122": {
        "exp": "\u2013vsiar[V\u2192V]",
        "exp_display": "\u2013vsiar",
        "description": "even more to completion",
        "postverb": "even more to completion",
        "match_case": true
    },
    "123": {
        "exp": "\u2013vyiar[V\u2192V]",
        "exp_display": "\u2013vyiar",
        "description": "even more to completion",
        "postverb": "even more to completion",
        "match_case": true
    },
    "124": {
        "exp": "\u2013vyirte[V\u2192V]",
        "exp_display": "\u2013vyirte",
        "description": "around here and there",
        "postverb": "around here and there",
        "match_case": true
    },
    "125": {
        "exp": "@~+yaaqe[V\u2192V]",
        "exp_display": "@\u02b8~+yaaqe",
        "description": "in vain (fruitlessly)",
        "postverb": "in vain (fruitlessly)",
        "match_case": true
    },
    "126": {
        "exp": "\u2013ya(g)ar[V\u2192V]",
        "exp_display": "\u2013ya\u0121ar",
        "subj": "it",
        "is": true,
        "description": "very cutely or dearly",
        "gen_preverb": "very cutely or dearly",
        "past_preverb": "very cutely or dearly",
        "inf_preverb": "very cutely or dearly",
        "ger_preverb": "very cutely or dearly",
        "match_case": true
    },
    "127": {
        "exp": "\u2013yagar[V\u2192V]",
        "exp_display": "\u2013yagar",
        "subj": "it",
        "is": true,
        "description": "very cutely or dearly",
        "gen_preverb": "very cutely or dearly",
        "past_preverb": "very cutely or dearly",
        "inf_preverb": "very cutely or dearly",
        "ger_preverb": "very cutely or dearly",
        "match_case": true
    },
    "129": {
        "exp": "@~+yalqar[V\u2192V]",
        "exp_display": "@\u02b8~+yalqar",
        "description": "without recompense",
        "postverb": "without recompense",
        "match_case": true
    },
    "131": {
        "exp": "@~+yaqlir[V\u2192V]",
        "exp_display": "@\u02b8~+yaqlir",
        "subj": "he",
        "is": true,
        "description": "finally",
        "gen_preverb": "finally",
        "past_preverb": "finally",
        "inf_preverb": "finally",
        "ger_preverb": "finally",
        "match_case": true
    },
    "133": {
        "exp": "@~+yarar[V\u2192V]",
        "exp_display": "@\u02b8~+yarar",
        "description": "early",
        "postverb": "early",
        "match_case": true
    },
    "134": {
        "exp": "@~+yarar(ar)[V\u2192V]",
        "exp_display": "@\u02b8~+yarar(ar)",
        "description": "very early",
        "postverb": "very early",
        "match_case": true
    },
    "135": {
        "exp": "@~+yarpiar[V\u2192V]",
        "exp_display": "@\u02b8~+yarpiar",
        "subj": "he",
        "is": true,
        "description": "almost",
        "gen_preverb": "almost",
        "past_preverb": "almost",
        "inf_preverb": "almost",
        "ger_preverb": "almost",
        "match_case": true
    },
    "136": {
        "exp": "~+yarpigar[V\u2192V]",
        "exp_display": "~+yarpigar",
        "subj": "he",
        "is": true,
        "description": "almost",
        "gen_preverb": "almost",
        "past_preverb": "almost",
        "inf_preverb": "almost",
        "ger_preverb": "almost",
        "match_case": true
    },
    "137": {
        "exp": "@~+yartur[V\u2192V]",
        "exp_display": "@\u02b8~+yartur",
        "subj": "he",
        "is": true,
        "description": "going to",
        "gen_preverb": "going to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "go",
        "inf_preverb_after": "g",
        "ger_preverb": "going",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "138": {
        "exp": "@~+yaurciiqe[V\u2192V]",
        "exp_display": "@\u02b8~+yaurciiqe",
        "subj": "he",
        "is": true,
        "description": "starting and continuing to",
        "gen_preverb": "starting and continuing to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "start and continue to",
        "inf_preverb_after": "i",
        "ger_preverb": "starting and continuing to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "139": {
        "exp": "@~+yaurte[V\u2192V]",
        "exp_display": "@\u02b8~+yaurte",
        "subj": "he",
        "is": true,
        "description": "now able to",
        "gen_preverb": "now able to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be now able to",
        "inf_preverb_after": "i",
        "ger_preverb": "being now able to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "140": {
        "exp": "@~\u2013yu[V\u2192V]",
        "exp_display": "@\u02b8~\u2013yu",
        "subj": "he",
        "is": true,
        "description": "well able to",
        "gen_preverb": "well able to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be well able to",
        "inf_preverb_after": "i",
        "ger_preverb": "being well able to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "141": {
        "exp": "@~+yuar[V\u2192V]",
        "exp_display": "@\u02b8~+yuar",
        "subj": "",
        "is": false,
        "description": "",
        "gen_preverb": "",
        "gen_preverb_after": "",
        "past_preverb": "",
        "past_preverb_after": "",
        "inf_preverb": "",
        "inf_preverb_after": "i",
        "ger_preverb": "",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "142": {
        "exp": "@~+yug[V\u2192V]",
        "exp_display": "@\u02b8~+yug",
        "subj": "he",
        "is": false,
        "description": "wants to",
        "gen_preverb": "wants to",
        "gen_preverb_after": "i",
        "past_preverb": "wanted to",
        "past_preverb_after": "i",
        "inf_preverb": "want to",
        "inf_preverb_after": "i",
        "ger_preverb": "wanting to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "143": {
        "exp": "@~+yugar[V\u2192V]",
        "exp_display": "@\u02b8~+yugar",
        "subj": "he",
        "is": false,
        "description": "enjoys ^his^",
        "gen_preverb": "enjoys ^his^",
        "gen_preverb_after": "g",
        "past_preverb": "enjoyed ^his^",
        "past_preverb_after": "g",
        "inf_preverb": "enjoy ^his^",
        "inf_preverb_after": "g",
        "ger_preverb": "enjoying ^his^",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "144": {
        "exp": "@~+yugcali[V\u2192V]",
        "exp_display": "@\u02b8~+yugcali",
        "description": "heartily",
        "postverb": "heartily",
        "match_case": true
    },
    "146": {
        "exp": "@~+yugnairute[V\u2192V]",
        "exp_display": "@\u02b8~+yugnairute",
        "subj": "it",
        "is": true,
        "description": "definitely no longer going to",
        "gen_preverb": "definitely no longer going to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be definitely no longer going to",
        "inf_preverb_after": "i",
        "ger_preverb": "being definitely no longer going to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "147": {
        "exp": "@~+yugnaite1[V\u2192V]",
        "exp_display": "@\u02b8~+yugnaite\u00b0",
        "subj": "it",
        "is": true,
        "description": "definitely not going to ",
        "gen_preverb": "definitely not going to ",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be definitely not going to ",
        "inf_preverb_after": "i",
        "ger_preverb": "being definitely not going to ",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "149": {
        "exp": "@~+yugnarqe1[V\u2192V]",
        "exp_display": "@\u02b8~+yugnarqe",
        "subj": "he",
        "is": true,
        "description": "probably",
        "gen_preverb": "probably",
        "past_preverb": "probably",
        "inf_preverb": "probably",
        "ger_preverb": "probably",
        "match_case": true
    },
    "150": {
        "exp": "@~+yugnarqe2[V\u2192V]",
        "exp_display": "@\u02b8~+yugnarqe",
        "subj": "it",
        "is": true,
        "description": "such as to make one want to",
        "gen_preverb": "such as to make one want to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be such as to make one want to",
        "inf_preverb_after": "i",
        "ger_preverb": "being such as to make one want to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "151": {
        "exp": "@~+yugnga[V\u2192V]",
        "exp_display": "@\u02b8~+yugnga",
        "subj": "he",
        "is": true,
        "description": "able to",
        "gen_preverb": "able to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be able to",
        "inf_preverb_after": "i",
        "ger_preverb": "being able to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "152": {
        "exp": "@~+yugyaaqe[V\u2192V]",
        "exp_display": "@\u02b8~+yugyaaqe",
        "subj": "he",
        "is": false,
        "description": "wants (provided it is all right) to",
        "gen_preverb": "wants (provided it is all right) to",
        "gen_preverb_after": "i",
        "past_preverb": "wanted (provided it was all right) to",
        "past_preverb_after": "i",
        "inf_preverb": "want (provided it is all right) to",
        "inf_preverb_after": "i",
        "ger_preverb": "wanting (provided it is all right) to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "153": {
        "exp": "@~\u2013yuirute[V\u2192V]",
        "exp_display": "@\u02b8~\u2013yuirute",
        "subj": "he",
        "is": true,
        "description": "no longer",
        "gen_preverb": "no longer",
        "gen_preverb_after": "g",
        "past_preverb": "",
        "past_preverb_after": "g",
        "inf_preverb": "be no longer",
        "inf_preverb_after": "g",
        "ger_preverb": "being no longer",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "154": {
        "exp": "@~\u2013yuite[V\u2192V]",
        "exp_display": "@\u02b8~\u2013yuite\u00b0",
        "subj": "he",
        "is": true,
        "description": "never",
        "gen_preverb": "never",
        "gen_preverb_after": "g",
        "past_preverb": "",
        "past_preverb_after": "g",
        "inf_preverb": "be never",
        "inf_preverb_after": "g",
        "ger_preverb": "being never",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "155": {
        "exp": "@~+yukaar(ar)[V\u2192V]",
        "exp_display": "@\u02b8~+yukaar(ar)",
        "subj": "he",
        "is": true,
        "description": "ready to",
        "gen_preverb": "ready to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "be ready to",
        "inf_preverb_after": "i",
        "ger_preverb": "being ready to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "158": {
        "exp": "@~\u2013yunari[V\u2192V]",
        "exp_display": "@\u02b8~\u2013yunari",
        "subj": "it",
        "is": true,
        "description": "the proper time to",
        "gen_preverb": "the proper time to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "",
        "inf_preverb_after": "i",
        "ger_preverb": "",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "159": {
        "exp": "@~\u2013yunarqe[V\u2192V]",
        "exp_display": "@\u02b8~\u2013yunarqe",
        "subj": "it",
        "is": true,
        "description": "possible to",
        "gen_preverb": "possible to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "",
        "inf_preverb_after": "i",
        "ger_preverb": "",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "160": {
        "exp": "@~+yunqegg[V\u2192V]",
        "exp_display": "@\u02b8~+yunqegg",
        "subj": "he",
        "is": false,
        "description": "loves",
        "gen_preverb": "loves",
        "gen_preverb_after": "g",
        "past_preverb": "loved",
        "past_preverb_after": "g",
        "inf_preverb": "",
        "inf_preverb_after": "i",
        "ger_preverb": "",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "161": {
        "exp": "@~+yunrite[V\u2192V]",
        "exp_display": "@\u02b8~+yunrite\u00b0",
        "subj": "he",
        "is": true,
        "description": "continuing not to",
        "gen_preverb": "continuing not to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "",
        "inf_preverb_after": "i",
        "ger_preverb": "",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "162": {
        "exp": "@~+yuuma[V\u2192V]",
        "exp_display": "@\u02b8~+yuuma",
        "subj": "he",
        "is": true,
        "description": "able to",
        "gen_preverb": "able to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "",
        "inf_preverb_after": "i",
        "ger_preverb": "",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "163": {
        "exp": "@~+yuumiir(ar)te[V\u2192V]",
        "exp_display": "@\u02b8~+yuumiir(ar)te",
        "subj": "he",
        "is": false,
        "description": "no longer wants to",
        "gen_preverb": "no longer wants to",
        "gen_preverb_after": "i",
        "past_preverb": "no longer wanted to",
        "past_preverb_after": "i",
        "inf_preverb": "",
        "inf_preverb_after": "i",
        "ger_preverb": "",
        "ger_preverb_after": "g",
        "match_case": false
    },
    "164": {
        "exp": "@~+yuumiite[V\u2192V]",
        "exp_display": "@\u02b8~+yuumiite\u00b0",
        "subj": "he",
        "is": false,
        "description": "not care to",
        "gen_preverb": "not care to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "not care to",
        "inf_preverb_after": "i",
        "ger_preverb": "not caring to",
        "ger_preverb_after": "i",
        "match_case": false
    },
    "165": {
        "exp": "@~+yuumir[V\u2192V]",
        "exp_display": "@\u02b8~+yuumir",
        "subj": "he",
        "is": true,
        "description": "yearning to",
        "gen_preverb": "yearning to",
        "gen_preverb_after": "i",
        "past_preverb": "",
        "past_preverb_after": "i",
        "inf_preverb": "yearn to",
        "inf_preverb_after": "i",
        "ger_preverb": "yearning to",
        "ger_preverb_after": "i",
        "match_case": false
    }
}

export const verbPostbases = {
  // '0':{
  //   // id: 0,
  //   description: 'is probably',
  //   englishModifier: (english) => { return 'probably '+ english; },
  //   expression: 'palliq',
  //   expression_conditional: '',
  //   conditional_rule: '',
  //   priority: 1,
  //   tense:'',
  //   allowable_next_ids: [1]
  // },
//   {
//     id: 1,
//     description: 'is evidently (without being observed)',
//     englishModifier: (english) => { return 'evidently '+ english; },
//     expression: '-2ini\\',
//     expression_conditional: '',
//     conditional_rule: '',
//     priority: 1,
//     tense:'',
//     allowable_next_ids: [0]
//   },
//   {
//     id: 2,
//     description: 'is no longer able to',
//     englishModifier: (english) => { return 'no longer able to '+ english; },
//     expression: '+(s)ciigali\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1,3]
//   },
//   {
//     id: 3,
//     description: 'is not able to',
//     englishModifier: (english) => { return 'not able to '+ english; },
//     expression: '+(s)ciigate\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1,2]
//   },

// notis = [1,2,6,7,10]
// future = [1,2]
// infinitive = [1,2,6,8,9,10,11]

// if not added second for notis, use does

  1:{
    // id: 4,
    description: 'will',
    englishModifier: (english) => { return 'will '+ english; },
    englishModifierInfinitive: (english) => { return 'will '+ english; },
    englishModifierGerund: (english) => { return 'will '+ english; },
    englishModifierPast: (english) => { return 'will '+ english; },
    expression: '+ciqe|@ciiqe[V→V]',
    // tense:'future',
    allowable_next_ids: [10, 11, 5, 6, 8, 7, 12, 9],
  },
  2:{
    // id: 4,
    description: 'will not',
    englishModifier: (english) => { return 'will not '+ english; },
    englishModifierInfinitive: (english) => { return 'will not '+ english; },
    englishModifierGerund: (english) => { return 'will not '+ english; },
    englishModifierPast: (english) => { return "won't "+ english; },
    expression: '@~+ngaite[V→V]',
    // tense:'future',
    allowable_next_ids: [6, 10, 11, 9, 12, 7, 8],
  },
  3:{
    // id: 4,
    description: 'probably',
    englishModifier: (english) => { return 'probably '+ english; },
    englishModifierInfinitive: (english) => { return 'probably '+ english; },
    englishModifierGerund: (english) => { return 'probably '+ english; },
    englishModifierPast: (english) => { return 'probably '+ english; },
    expression: '@~+yugnarqe2[V→V]',
    // tense:'',
    allowable_next_ids: [1, 2, 6, 4],
  },
  4:{
    // id: 4,
    description: 'not',
    englishModifier: (english) => { return 'not '+ english; },
    englishModifierInfinitive: (english) => { return 'not '+ english; },
    englishModifierGerund: (english) => { return 'not '+ english; },
    englishModifierPast: (english) => { return 'not '+ english; },
    expression: '–nrite[V→V]',
    // tense:'',
    allowable_next_ids: [6, 5],
  },
  5:{
    // id: 4,
    description: 'deliberately (purposefully)',
    englishModifier: (english) => { return 'deliberately (purposefully) '+ english; },
    englishModifierInfinitive: (english) => { return 'deliberately (purposefully) '+ english; },
    englishModifierGerund: (english) => { return 'deliberately (purposefully) '+ english; },
    englishModifierPast: (english) => { return 'deliberately (purposefully) '+ english; },
    expression: 'saaġi',
    // tense:'',
    allowable_next_ids: [4],
  },

  12:{
    // id: 4,
    description: 'always (regularly)',
    englishModifier: (english) => { return 'always (regularly) '+ english; },
    englishModifierInfinitive: (english) => { return 'always (regularly) '+ english; },
    englishModifierGerund: (english) => { return 'always (regularly) '+ english; },
    englishModifierPast: (english) => { return 'always (regularly) '+ english; },
    expression: '–lar[V→V]',
    // tense:'',
    allowable_next_ids: [6, 11]
  },

  6:{
    // id: 4,
    description: 'wants to',
    englishModifier: (english) => { return 'wanting to '+ english; },
    englishModifierInfinitive: (english) => { return 'want to '+ english; },
    englishModifierGerund: (english) => { return 'wanting to '+ english; },
    englishModifierPast: (english) => { return 'wanted to '+ english; },
    expression: '@~+yug[V→V]',
    // tense:'',
    allowable_next_ids: [11, 9],
  },

  11:{
    // id: 4,
    description: 'beginning to',
    englishModifier: (english) => { return 'beginning to '+ english; },
    englishModifierInfinitive: (english) => { return 'begin to '+ english; },
    englishModifierGerund: (english) => { return 'beginning to '+ english; },
    englishModifierPast: (english) => { return 'began to '+ english; },
    expression: 'rraqsi',
    // tense:'',
    allowable_next_ids: [6]
  },

  10:{
    // id: 4,
    description: 'likes',
    englishModifier: (english) => { return 'likes '+ english; },
    englishModifierInfinitive: (english) => { return 'like '+ english; },
    englishModifierGerund: (english) => { return 'liking '+ english; },
    englishModifierPast: (english) => { return 'liked '+ english; },
    expression: 'llatu',
    // tense:'',
    allowable_next_ids: []
  },

  7:{
    // id: 4,
    description: 'dislikes',
    englishModifier: (english) => { return 'dislikes '+ english; },
    englishModifierInfinitive: (english) => { return 'dislike '+ english; },
    englishModifierGerund: (english) => { return 'disliking '+ english; },
    englishModifierPast: (english) => { return 'disliked '+ english; },
    expression: 'sulait',
    // tense:'',
    allowable_next_ids: []
  },

  8:{
    // id: 4,
    description: 'not able to',
    englishModifier: (english) => { return 'unable to '+ english; },
    englishModifierInfinitive: (english) => { return 'be unable to '+ english; },
    englishModifierGerund: (english) => { return 'being unable to '+ english; },
    englishModifierPast: (english) => { return 'unable to '+ english; },
    expression: '+(s)ciigate[V→V]',
    // tense:'',
    allowable_next_ids: []
  },

  9:{
    // id: 4,
    description: 'able to',
    englishModifier: (english) => { return 'able to '+ english; },
    englishModifierInfinitive: (english) => { return 'be able to '+ english; },
    englishModifierGerund: (english) => { return 'being able to '+ english; },
    englishModifierPast: (english) => { return 'able to '+ english; },
    expression: '@~+yugnga[V→V]',
    // tense:'',
    allowable_next_ids: []
  },



//   {
//     id: 5,
//     description: 'past tense',
//     englishModifier: (english) => { return ''+ english; },
//     expression: '-2ru\\',
//     expression_conditional: '',
//     priority: 3,
//     conditional_rule: '',
//     tense:'past',
//     allowable_next_ids: [7]
//   },
//   {
//     id: 6,
//     description: 'not yet',
//     englishModifier: (english) => { return 'not yet '+ english; },
//     expression: '-ksaite\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,7]
//   },
//   {
//     id: 7,
//     description: 'future tense',
//     englishModifier: (english) => { return ''+ english},
//     expression: '+ciqe\\',
//     expression_conditional: '@ciiqe\\',  // conditional te_ending
//     priority: 3,
//     conditional_rule: 'attaching_to_te',  // defined later and if satisfied display expression_conditional
//     tense:'future',
//     allowable_next_ids: [0,1,5,10]
//   },
//   {
//     id: 8,
//     description: 'will not',
//     englishModifier: (english) => { return 'not '+  english; },
//     expression: '@~+6aite\\',
//     expression_conditional: '',
//     priority: 3,
//     conditional_rule: '',
//     tense:'future',
//     allowable_next_ids: [0,1,7,10]
//   },
//   {
//     id: 9,
//     description: 'will soon',
//     englishModifier: (english) => { return 'soon '+ english; },
//     expression: '@~+niarar\\',
//     expression_conditional: '',
//     priority: 3,
//     conditional_rule: '',
//     tense:'future',
//     allowable_next_ids: [0,1,5,6,7,10]
//   },
//   {
//     id: 10,
//     description: 'about to',
//     englishModifier: (english) => { return 'about to '+ english; },
//     expression: '-qatar\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1,7]
//   },
//   {
//     id: 11,
//     description: 'repeatedly',
//     englishModifier: (english) => { return 'repeatedly '+ english; },
//     expression: '-lar\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1]
//   },
//   {
//     id: 12,
//     description: 'doing it again',
//     englishModifier: (english) => { return '(again) '+ english; },
//     expression: '-nqigte\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1]
//   },
//   {
//     id: 13,
//     description: 'almost',
//     englishModifier: (english) => { return 'almost '+ english; },
//     expression: '@~+yarpiar\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1]
//   },
//   {
//     id: 14,
//     description: 'never',
//     englishModifier: (english) => { return 'never '+ english; },
//     expression: '@-~yuite\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1]
//   },
//   {
//     id: 15,
//     description: 'no longer',
//     englishModifier: (english) => { return 'no longer '+ english; },
//     expression: '-nrir\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,27]
//   },
//   {
//     id: 16,
//     description: 'trying (unsuccessfully) to',
//     englishModifier: (english) => { return 'trying (unsuccessfully) to '+ english; },
//     englishModifierInfinitive: (english) => { return 'try (unsuccessfully) to '+ english; },
//     englishModifierGerund: (english) => { return 'trying (unsuccessfully) to '+ english; },
//     expression: '@~+yaaqe\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,17,19]
//   },
//   {
//     id: 17,
//     description: 'trying despite difficulties to',
//     englishModifier: (english) => { return 'trying despite difficulties to '+ english; },
//     englishModifierInfinitive: (english) => { return 'try despite difficulties to '+ english; },
//     englishModifierGerund: (english) => { return 'trying despite difficulties to '+ english; },
//     expression: '-qcaar(ar)\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,16,18]
//   },
//   {
//     id: 18,
//     description: 'trying to',
//     englishModifier: (english) => { return 'trying to '+ english; },
//     englishModifierInfinitive: (english) => { return 'try to '+ english; },
//     englishModifierGerund: (english) => { return 'trying to '+ english; },
//     expression: '-6naqe\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,16,17]
//   },
//   {
//     id: 19,
//     description: 'excessively (too much)',
//     englishModifier: (english) => { return 'excessively '+ english; },
//     expression: '-3iyaag\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1]
//   },
//   {
//     id: 20,
//     description: 'to be more or better at',
//     englishModifier: (english) => { return '(being more or better at) '+ english; },
//     expression: '-nru\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [1]
//   },
//   {
//     id: 21,
//     description: 'loves to',
//     englishModifier: (english) => { return 'loves to '+ english; },
//     englishModifierInfinitive: (english) => { return 'love to '+ english; },
//     englishModifierGerund: (english) => { return 'loving to '+ english; },
//     expression: '@~+yunqe4\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,7,8]
//   },
//   {
//     id: 22,
//     description: 'no longer wants to',
//     englishModifier: (english) => { return 'no longer wants to '+ english; },
//     englishModifierInfinitive: (english) => { return 'no longer want to '+ english; },
//     englishModifierGerund: (english) => { return 'no longer wanting to '+ english; },
//     expression: '@~+yuumiir(ar)te\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,7,8]
//   },
//   {
//     id: 23,
//     description: 'not care to',
//     englishModifier: (english) => { return 'not care to '+ english; },
//     englishModifierInfinitive: (english) => { return 'not care to '+ english; },
//     englishModifierGerund: (english) => { return 'not caring to '+ english; },
//     expression: '@~+yuumiite\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,7,8]
//   },
//   {
//     id: 24,
//     description: 'yearns to',
//     englishModifier: (english) => { return 'yearns to '+ english; },
//     englishModifierInfinitive: (english) => { return 'yearn to '+ english; },
//     englishModifierGerund: (english) => { return 'yearning to '+ english; },
//     expression: '@~+yuumir\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,7,8]
//   },
//   {
//     id: 25,
//     description: 'wants to',
//     englishModifier: (english) => { return 'wants to '+ english; },
//     englishModifierInfinitive: (english) => { return 'want to '+ english; },
//     englishModifierGerund: (english) => { return 'wanting to '+ english; },
//     expression: '@~+yug\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,7,8]
//   },
//   {
//     id: 26,
//     description: 'enjoys doing',
//     englishModifier: (english) => { return 'enjoying '+ english; },
//     englishModifierInfinitive: (english) => { return 'enjoy '+ english; },
//     englishModifierGerund: (english) => { return 'enjoying '+ english; },
//     expression: '@~+yugar\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,7,8]
//   },
//   {
//     id: 27,
//     description: 'not',
//     englishModifier: (english) => { return 'not '+ english; },
//     expression: '-nrite\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1]
//   },
//   // {
//   //   id: 28,
//   //   description: 'to ask one to',
//   //   englishModifier: (english) => { return 'to ask one to '+ english; },
//   //   expression: 'sqe-\\',
//   //   expression_conditional: '',
//   //   conditional_rule: '',
//   //   tense:'',
//   //   allowable_next_ids: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
//   // },
//   {
//     id: 28,
//     description: 'in the process of',
//     englishModifier: (english) => { return 'in the process of '+ english; },
//     expression: '@~+yartur\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,2,3,4,5,6,7,8,9,10,19]
//   },
//   {
//     id: 29,
//     description: 'definitely no longer going to',
//     englishModifier: (english) => { return 'definitely no longer going to '+ english; },
//     expression: '@~+yugnairute\\',
//     expression_conditional: '',
//     priority: 1,
//     conditional_rule: '',
//     tense:'',
//     allowable_next_ids: [0,1,3,4,8,10], // only refers to the postbases, not the endings
//   }
};
export const nounPostbases = {


  13:{
    // id: 4,
    description: 'good',
    englishModifier: (english) => { return 'good '+ english; },
    englishModifierPlural: (english) => { return 'good '+ english; },

    expression: '–kegtaar(ar*)[N→N]',
    // tense:'future',
    allowable_next_ids: [17,18,19,20,21,22,23,24,25],
  },
  14:{
    // id: 4,
    description: 'big',
    englishModifier: (english) => { return 'big '+ english; },
    englishModifierPlural: (english) => { return 'big '+ english; },
    expression: 'qpak',
    // tense:'future',
    allowable_next_ids: [17,18,19,20,21,22,23,24,25],
  },
  15:{
    // id: 4,
    description: 'bad',
    englishModifier: (english) => { return 'bad '+ english; },
    englishModifierPlural: (english) => { return 'bad '+ english; },
    expression: 'pałłuk',
    // tense:'',
    allowable_next_ids: [17,18,19,20,21,22,23,24,25],
  },
  16:{
    // id: 4,
    description: 'small',
    englishModifier: (english) => { return 'small '+ english; },
    englishModifierPlural: (english) => { return 'small '+ english; },
    expression: 'ŋuluk',
    // tense:'',
    allowable_next_ids: [17,18,19,20,21,22,23,24,25],
  },
  17:{
    // id: 4,
    description: 'it is a N',
    englishModifier: (english) => { return 'a '+ english; },
    englishModifierPlural: (english) => { return ''+ english; },
    expression: 'u',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  18:{
    // id: 4,
    description: 'it is making N',
    englishModifier: (english) => { return 'making a '+ english; },
    englishModifierPlural: (english) => { return 'making a '+ english; },
    expression: 'liuq',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  19:{
    // id: 4,
    description: 'it is eating or using N',
    englishModifier: (english) => { return 'eating or using a '+ english; },
    englishModifierPlural: (english) => { return 'eating or using a '+ english; },
    expression: 'tuq',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  20:{
    // id: 4,
    description: 'it has a N',
    englishModifier: (english) => { return 'has a '+ english; },
    englishModifierPlural: (english) => { return 'have a '+ english; },
    expression: 'qaq',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  21:{
    // id: 4,
    description: 'it has a small quantity of N',
    englishModifier: (english) => { return 'has a small quantity of '+ english; },
    englishModifierPlural: (english) => { return 'have a small quantity of '+ english; },
    expression: 'kit',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  22:{
    // id: 4,
    description: 'it lacks N',
    englishModifier: (english) => { return 'lacks a '+ english; },
    englishModifierPlural: (english) => { return 'lack a '+ english; },
    expression: 'it',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  23:{
    // id: 4,
    description: 'it is located at the N',
    englishModifier: (english) => { return 'located at the '+ english; },
    englishModifierPlural: (english) => { return 'located at the '+ english; },
    expression: '+N+Loc+Sg>miit',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  24:{
    // id: 4,
    description: 'it is coming from the N',
    englishModifier: (english) => { return 'coming from the '+ english; },
    englishModifierPlural: (english) => { return 'coming from the '+ english; },
    expression: '+N+Abl+Sg>miñŋaq',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
  25:{
    // id: 4,
    description: 'it is going to the N',
    englishModifier: (english) => { return 'going to the '+ english; },
    englishModifierPlural: (english) => { return 'going to the '+ english; },
    expression: '+N+Trm+Sg>muk',
    // tense:'',
    allowable_next_ids: [13,14,15,16],
  },
//   {
//     id: 0,
//     description: 'large',
//     englishModifier: (english) => { return 'large '+ english; },
//     expression_end: '-rpak',
//     expression_postbase: '-rpag\\',
//     expression_conditional_end: '',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:4,
//     tense:'',
//     allowable_next_ids: [1]
//   },
//   {
//     id: 1,
//     description: 'small',
//     englishModifier: (english) => { return 'small '+ english; },
//     expression_end: '-cuar',
//     expression_postbase: '-cuar\\',
//     expression_conditional_end: '-kcuar',
//     expression_conditional_postbase: '-kcuar(ar)\\',
//     conditional_rule: '',
//     priority:4,
//     tense:'',
//     allowable_next_ids: [0]
//   },
//   {
//     id: 2,
//     description: 'baby/little',
//     englishModifier: (english) => { return 'baby/little '+ english; },
//     expression_end: '-yagaq',
//     expression_postbase: '-yagar\\',
//     expression_conditional_end: '-yagaq',
//     expression_conditional_postbase: '-yagar\\',
//     conditional_rule: '',
//     priority:4,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 3,
//     description: 'good',
//     englishModifier: (english) => { return 'good '+ english; },
//     expression_end: '-kegtaar',
//     expression_postbase: '-kegtaar\\',
//     expression_conditional_end: '',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:4,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 4,
//     description: 'shabby',
//     englishModifier: (english) => { return 'shabby '+ english; },
//     expression_end: '-2er',
//     expression_postbase: '-2er\\',
//     expression_conditional_end: '-2er',
//     expression_conditional_postbase: '-2er\\',
//     conditional_rule: '',
//     priority:4,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 5,
//     description: 'genuine',
//     englishModifier: (english) => { return 'genuine '+ english; },
//     expression_end: '-piaq',
//     expression_postbase: '-piar\\',
//     expression_conditional_end: '-pik',
//     expression_conditional_postbase: '-pig\\',
//     conditional_rule: '',
//     priority:4,
//     tense:'past',
//     allowable_next_ids: []
//   },
//   {
//     id: 6,
//     description: 'fake',
//     englishModifier: (english) => { return 'fake '+ english; },
//     expression_end: '-(6)uaq',
//     expression_postbase: '-(6)uar\\',
//     expression_conditional_end: '',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:4,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 7,
//     description: 'many Ns',
//     englishModifier: (english) => { return 'many of them'+ english},
//     expression_end: '-rugaq',
//     expression_postbase: '-rugar\\',
//     expression_conditional_end: '',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:2,
//     tense:'noun_end',
//     allowable_next_ids: []
//   },
//   {
//     id: 8,
//     description: 'just a little',
//     englishModifier: (english) => { return 'just a little'+ english},
//     expression_end: '-5aq',
//     expression_postbase: '-5ar\\',
//     expression_conditional_end: '',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:2,
//     tense:'noun_end',
//     allowable_next_ids: []
//   },
//   {
//     id: 9,
//     description: 'N and other',
//     englishModifier: (english) => { return 'and another - only applies to people or animals '+ english; },
//     expression_end: ':(e)nkuk',
//     expression_postbase: ':(e)nkug\\',
//     expression_conditional_end: '',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:2,
//     tense:'noun_end',
//     allowable_next_ids: []
//   },
//   {
//     id: 10,
//     description: 'N and others',
//     englishModifier: (english) => { return 'and others - only applies to people or animals '+ english; },
//     expression_end: ':(e)nkut',
//     expression_postbase: ':(e)nkur\\',
//     expression_conditional_end: '',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:2,
//     tense:'noun_end',
//     allowable_next_ids: []
//   },
//   {
//     id: 11,
//     description: 'to hunt',
//     englishModifier: (english) => { return 'hunting '+ english; },
//     expression_postbase: '+cur\\',
//     expression_conditional_postbase: '+ssur\\',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 12,
//     description: 'to make',
//     englishModifier: (english) => { return 'making '+ english; },
//     expression_postbase: '-li\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 13,
//     description: 'to catch lots of',
//     englishModifier: (english) => { return 'catching lots of '+ english; },
//     expression_postbase: '-liqe\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 14,
//     description: 'to have lots of',
//     englishModifier: (english) => { return 'lots of '+ english; },
//     expression_postbase: '-lir\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 15,
//     description: 'to be occupied with',
//     englishModifier: (english) => { return 'occupied with '+ english; },
//     expression_postbase: '-liur\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 16,
//     description: 'to acquire',
//     englishModifier: (english) => { return 'acquiring '+ english; },
//     expression_postbase: '-6e\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 17,
//     description: 'to have',
//     englishModifier: (english) => { return ''+ english; },
//     expression_postbase: '-ngqerr\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 18,
//     description: 'the place does not have',
//     englishModifier: (english) => { return '(location) does not have '+ english; },
//     expression_postbase: '+taite\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 19,
//     description: 'the place has',
//     englishModifier: (english) => { return '(location) has '+ english; },
//     expression_postbase: '+ta6qe5\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 20,
//     description: 'to eat',
//     englishModifier: (english) => { return 'eating '+ english; },
//     expression_postbase: '+tur\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   },
//   {
//     id: 21,
//     description: 'to become',
//     englishModifier: (english) => { return 'become '+ english; },
//     expression_postbase: '~:(6)urte\\',
//     expression_conditional_postbase: '',
//     conditional_rule: '',
//     priority:1,
//     tense:'',
//     allowable_next_ids: []
//   }
};
